insert into rul_mod (id, scale_id, condition, priority, seqnum) values (-5110, 1002, 'com_api_flexible_data_pkg.get_flexible_value(''MAS'', ''ENTTMRCH'', opr_api_shared_data_pkg.get_participant(''PRTYACQ'').merchant_id) = ''Z'' and upper(opr_api_shared_data_pkg.get_operation().merchant_name) like ''MP#%'' and aup_api_tag_pkg.get_tag_value(i_auth_id => opr_api_shared_data_pkg.get_operation().id, i_tag_reference => ''DF8E0A'') in (''Z04'', ''Z05'', ''Z65'', ''Z66'', ''Z06'', ''Z07'', ''Z67'', ''Z08'', ''Z09'')', 140, 1)
/
insert into rul_mod (id, scale_id, condition, priority, seqnum) values (-5111, -5012, ':IS_REVERSAL = 1', 10, 1)
/
insert into rul_mod (id, scale_id, condition, priority, seqnum) values (-5113, 1019, 'opr_api_shared_data_pkg.get_operation().proc_stage = ''OPCM5001'' and com_api_flexible_data_pkg.get_flexible_value(''MAS'', ''ENTTMRCH'', opr_api_shared_data_pkg.get_participant(''PRTYACQ'').merchant_id) = ''Z'' and upper(opr_api_shared_data_pkg.get_operation().merchant_name) like ''MP#%'' and opr_api_shared_data_pkg.get_operation().terminal_type in (''TRMT0002'') and aup_api_tag_pkg.get_tag_value(i_auth_id => opr_api_shared_data_pkg.get_operation().id, i_tag_reference => ''DF8E0A'') in (''Z04'', ''Z05'', ''Z65'', ''Z66'', ''Z06'', ''Z07'', ''Z67'', ''Z08'', ''Z09'')', 120, 1)
/
insert into rul_mod (id, scale_id, condition, priority, seqnum) values (-5112, 1019, 'opr_api_shared_data_pkg.get_operation().proc_stage = ''OPCM5001'' and com_api_flexible_data_pkg.get_flexible_value(''MAS'', ''ENTTMRCH'', opr_api_shared_data_pkg.get_participant(''PRTYACQ'').merchant_id) = ''Z'' and upper(opr_api_shared_data_pkg.get_operation().merchant_name) like ''MP#%'' and opr_api_shared_data_pkg.get_operation().terminal_type in (''TRMT0003'') and aup_api_tag_pkg.get_tag_value(i_auth_id => opr_api_shared_data_pkg.get_operation().id, i_tag_reference => ''DF8E0A'') in (''Z04'', ''Z05'', ''Z65'', ''Z66'', ''Z06'', ''Z07'', ''Z67'', ''Z08'', ''Z09'')', 110, 1)
/
insert into rul_mod (id, scale_id, condition, priority, seqnum) values (-5114, 5001, 'opr_api_shared_data_pkg.get_operation().msg_type = ''MSGTBTCH'' and :POS_BATCH_TRANS_TYPE IN (''736'', ''773'')', 10, 1)
/
