create table sec_rsa_key (
    id                  number(12)
    , seqnum            number(4)
    , object_id         number(16)
    , entity_type       varchar2(8)
    , lmk_id            number(4)
    , key_type          varchar2(8)
    , key_index         number(4)
    , expir_date        date
    , sign_algorithm    varchar2(8)
    , modulus_length    number(4)
    , exponent          varchar2(256)
    , public_key        varchar2(2048)
    , private_key       varchar2(2048)
    , public_key_mac    varchar2(16)
    , standard_key_type varchar2(8)
    , generate_date     date
    , generate_user_id  number(8)
)
/

comment on table sec_rsa_key is 'RSA crypto keys store'
/
comment on column sec_rsa_key.id is 'Identifier'
/
comment on column sec_rsa_key.seqnum is 'Sequence number. Describe data version'
/
comment on column sec_rsa_key.object_id is 'Owner object identifier'
/
comment on column sec_rsa_key.entity_type is 'Owner entity type'
/
comment on column sec_rsa_key.lmk_id is 'HSM LMK was used to get key cryptogram'
/
comment on column sec_rsa_key.key_type is 'Key type'
/
comment on column sec_rsa_key.key_index is 'Key index'
/
comment on column sec_rsa_key.expir_date is 'Key expiration date'
/
comment on column sec_rsa_key.sign_algorithm is 'Signature algorithm'
/
comment on column sec_rsa_key.modulus_length is 'Public key modulus length in bit'
/
comment on column sec_rsa_key.exponent is 'Public key exponent'
/
comment on column sec_rsa_key.public_key is 'Public key'
/
comment on column sec_rsa_key.private_key is 'Private key'
/
comment on column sec_rsa_key.public_key_mac is 'MAC of public component'
/
comment on column sec_rsa_key.standard_key_type is 'Communication standard specific key type'
/
comment on column sec_rsa_key.generate_date is 'Date when key was generated.'
/
comment on column sec_rsa_key.generate_user_id is 'User who initiate key generation if key was generated by manual operation.'
/
