create table sec_des_key (
    id                  number(12)
    , seqnum            number(4)
    , object_id         number(16)
    , entity_type       varchar2(8)
    , lmk_id            number(4)
    , key_type          varchar2(8)
    , key_index         number(4)
    , key_length        number(4)
    , key_value         varchar2(48)
    , key_prefix        varchar2(50)
    , check_value       varchar2(6)
    , standard_key_type varchar2(8)
    , generate_date     date
    , generate_user_id  number(8)
)
/

comment on table sec_des_key is 'DES crypto keys store. Keys using for interaction between devices, networks and others outer systems.'
/
comment on column sec_des_key.id is 'Primary key'
/
comment on column sec_des_key.seqnum is 'Sequence number. Describe data version'
/
comment on column sec_des_key.object_id is 'Object identifier using key'
/
comment on column sec_des_key.entity_type is 'Entity type using key'
/
comment on column sec_des_key.lmk_id is 'HSM LMK was used to get key cryptogram'
/
comment on column sec_des_key.key_type is 'Key type (SDKT dictionary)'
/
comment on column sec_des_key.key_index is 'Key index'
/
comment on column sec_des_key.key_length is 'Key length (16 - single, 32 - double, 48 - triple)'
/
comment on column sec_des_key.key_value is 'DES key value'
/
comment on column sec_des_key.key_prefix is 'Key prefix. Specify key type and using for key scheme identification by HSM'
/
comment on column sec_des_key.check_value is 'Check value'
/
comment on column sec_des_key.standard_key_type is 'Communication standard specific key type'
/
comment on column sec_des_key.generate_date is 'Date when key was generated.'
/
comment on column sec_des_key.generate_user_id is 'User who initiate key generation if key was generated by manual operation.'
/

comment on column sec_des_key.key_type is 'Key type (ENKT dictionary)'
/
