create table sec_hmac_key (
    id                  number(12)
    , seqnum            number(4)
    , object_id         number(16)
    , entity_type       varchar2(8)
    , lmk_id            number(4)
    , key_index         number(4)
    , key_length        number(4)
    , key_value         varchar2(48)
    , generate_date     date
    , generate_user_id  number(8)
)
/

comment on table sec_hmac_key is 'HMAC keys store. Keys using for generate an HMAC.'
/
comment on column sec_hmac_key.id is 'Primary key'
/
comment on column sec_hmac_key.seqnum is 'Sequence number. Describe data version'
/
comment on column sec_hmac_key.object_id is 'Object identifier using key'
/
comment on column sec_hmac_key.entity_type is 'Entity type using key'
/
comment on column sec_hmac_key.lmk_id is 'HSM LMK was used to get key cryptogram'
/
comment on column sec_hmac_key.key_index is 'Key index'
/
comment on column sec_hmac_key.key_length is 'Key length (16 - single, 32 - double, 48 - triple)'
/
comment on column sec_hmac_key.key_value is 'Key value'
/
comment on column sec_hmac_key.generate_date is 'Date when key was generated.'
/
comment on column sec_hmac_key.generate_user_id is 'User who initiate key generation if key was generated by manual operation.'
/

