-- User data tablespace
CREATE TABLESPACE user_data_tbs LOGGING
     DATAFILE '/oradata/sv/user_data01.dbf' SIZE 1G AUTOEXTEND ON NEXT 64K MAXSIZE UNLIMITED
     EXTENT MANAGEMENT LOCAL
     SEGMENT SPACE MANAGEMENT AUTO;
