#!/bin/sh
# chkconfig: 345 99 10
# description: Oracle auto start-stop script.
#
# Set ORA_HOME to be equivalent to the $ORACLE_HOME
# from which you wish to execute dbstart and dbshut;
#
# Set ORA_OWNER to the user id of the owner of the 
# Oracle database in ORA_HOME.

#ORA_HOME=/u01/app/oracle/product/10.2.0/db_1
#ORA_HOME=/u01/app/oracle/product/11.1.0/db_1
ORA_HOME=/oracle/product/11.2.0
ORA_OWNER=oracle

if [ ! -f $ORA_HOME/bin/dbstart ]
then
    echo "Oracle startup: cannot start"
    exit
fi

case "$1" in
    'start')
        # Start the Oracle databases:
        # The following command assumes that the oracle login 
        # will not prompt the user for any values
        #echo "Starting oracle..."
        #su - $ORA_OWNER -c "$ORA_HOME/bin/dbstart $ORA_HOME"
        su - oracle -c "echo \"startup\" | sqlplus -s \"/ as sysdba\" > /dev/null";
        su - oracle -c "lsnrctl start > /dev/null";
        touch /var/lock/subsys/oracle
        ;;
    'stop')
        # Stop the Oracle databases:
        # The following command assumes that the oracle login 
        # will not prompt the user for any values
        #echo "Stopping oracle..."
        #su - $ORA_OWNER -c "$ORA_HOME/bin/dbshut $ORA_HOME"
        su - oracle -c "lsnrctl stop > /dev/null";
        su - oracle -c "echo \"shutdown immediate\" | sqlplus -s \"/ as sysdba\" > /dev/null";
        rm -f /var/lock/subsys/oracle
        ;;
esac