package ru.bpc.sv2.campaign;

public interface CampaignConstants {
    String VIEW_CAMPAIGNS  = "VIEW_CAMPAIGNS";
    String ADD_CAMPAIGN    = "ADD_CAMPAIGN";
    String MODIFY_CAMPAIGN = "MODIFY_CAMPAIGN";
    String REMOVE_CAMPAIGN = "REMOVE_CAMPAIGN";

    String VIEW_CAMPAIGN_PRODUCTS  = "VIEW_CAMPAIGN_PRODUCTS";
    String ADD_CAMPAIGN_PRODUCT    = "ADD_CAMPAIGN_PRODUCT";
    String MODIFY_CAMPAIGN_PRODUCT = "MODIFY_CAMPAIGN_PRODUCT";
    String REMOVE_CAMPAIGN_PRODUCT = "REMOVE_CAMPAIGN_PRODUCT";

    String VIEW_CAMPAIGN_SERVICES  = "VIEW_CAMPAIGN_SERVICES";
    String ADD_CAMPAIGN_SERVICE    = "ADD_CAMPAIGN_SERVICE";
    String MODIFY_CAMPAIGN_SERVICE = "MODIFY_CAMPAIGN_SERVICE";
    String REMOVE_CAMPAIGN_SERVICE = "REMOVE_CAMPAIGN_SERVICE";

    String VIEW_CAMPAIGN_ATTRIBUTES  = "VIEW_CAMPAIGN_ATTRIBUTES";
    String ADD_CAMPAIGN_ATTRIBUTE    = "ADD_CAMPAIGN_ATTRIBUTE";
    String MODIFY_CAMPAIGN_ATTRIBUTE = "MODIFY_CAMPAIGN_ATTRIBUTE";
    String REMOVE_CAMPAIGN_ATTRIBUTE = "REMOVE_CAMPAIGN_ATTRIBUTE";

    String VIEW_CAMPAIGN_APPLICATIONS    = "VIEW_CAMPAIGN_APPLICATIONS";
    String ADD_CAMPAIGN_APPLICATION      = "ADD_CAMPAIGN_APPLICATIONS";
    String MODIFY_CAMPAIGN_APPLICATION   = "MODIFY_CAMPAIGN_APPLICATIONS";
    String REMOVE_CAMPAIGN_APPLICATION   = "REMOVE_CAMPAIGN_APPLICATIONS";
    String PROCESS_CAMPAIGN_APPLICATION  = "PROCESS_CAMPAIGN_APPLICATIONS";
}
