create table rcn_host_msg (
    id                        number(16)
  , part_key                  as (to_date(substr(lpad(to_char(id), 16, '0'), 1, 6), 'yymmdd'))  -- [@skip patch]
  , recon_type                varchar2(8)
  , msg_source                varchar2(8)
  , msg_date                  date
  , oper_id                   number(16)
  , recon_msg_id              number(16)
  , recon_status              varchar2(8)
  , recon_date                date
  , recon_inst_id             number(4)
  , oper_type                 varchar2(8)
  , msg_type                  varchar2(8)
  , sttl_type                 varchar2(8)
  , host_date                 date
  , oper_date                 date
  , oper_amount               number(22, 4)
  , oper_currency             varchar2(3)
  , oper_request_amount       number(22, 4)
  , oper_request_currency     varchar2(3)
  , oper_surcharge_amount     number(22, 4)
  , oper_surcharge_currency   varchar2(3)
  , originator_refnum         varchar2(36)
  , network_refnum            varchar2(36)
  , acq_inst_bin              varchar2(12)
  , status                    varchar2(8)
  , is_reversal               number(1)
  , merchant_number           varchar2(15)
  , mcc                       varchar2(4)
  , merchant_name             varchar2(200)
  , merchant_street           varchar2(200)
  , merchant_city             varchar2(200)
  , merchant_region           varchar2(3)
  , merchant_country          varchar2(3)
  , merchant_postcode         varchar2(10)
  , terminal_type             varchar2(8)
  , terminal_number           varchar2(8)
  , acq_inst_id               number(4)
  , card_mask                 varchar2(24)
  , card_seq_number           number(3)
  , card_expir_date           date
  , card_country              varchar2(3)
  , iss_inst_id               number(4)
  , auth_code                 varchar2(6)
)
/****************** partition start ********************
partition by range (part_key) interval(numtoyminterval(1, 'MONTH'))
(
    partition rcn_host_msg_p01 values less than (to_date('1-1-2017','DD-MM-YYYY'))
)
******************** partition end ********************/
/
comment on table rcn_host_msg is 'Host reconciliation messages'
/
comment on column rcn_host_msg.id is 'Record identifier'
/
comment on column rcn_host_msg.recon_type is 'Reconciliation type. (Dictionary RCNT).'
/
comment on column rcn_host_msg.msg_source is 'Message source. (Dictionary RMSC).'
/
comment on column rcn_host_msg.msg_date is 'Message date and time inserted into the table.'
/
comment on column rcn_host_msg.oper_id is 'Reference to operation. Not empty if a message loaded from SV operations.'
/
comment on column rcn_host_msg.recon_msg_id is 'Reference to reconciled message.'
/
comment on column rcn_host_msg.recon_status is 'Reconciliation status. (Dictionary RNST).'
/
comment on column rcn_host_msg.recon_date is 'Date and time of last reconciliation process on the message.'
/
comment on column rcn_host_msg.recon_inst_id is 'Reconciliation institution. For multi institution reconciliation.'
/
comment on column rcn_host_msg.oper_type is 'Operation type. (Dictionary OPTP).'
/
comment on column rcn_host_msg.msg_type is 'Message type. (Dictionary MSGT).'
/
comment on column rcn_host_msg.sttl_type is 'Settlement type. (Dictionary STTT).'
/
comment on column rcn_host_msg.host_date is 'Host date.'
/
comment on column rcn_host_msg.oper_date is 'Operation date.'
/
comment on column rcn_host_msg.oper_amount is 'Operation amount.'
/
comment on column rcn_host_msg.oper_currency is 'Operation currency.'
/
comment on column rcn_host_msg.oper_request_amount is 'Operation requested amount.'
/
comment on column rcn_host_msg.oper_request_currency is 'Operation requested amount currency.'
/
comment on column rcn_host_msg.oper_surcharge_amount is 'Operation surcharge amount.'
/
comment on column rcn_host_msg.oper_surcharge_currency is 'Operation surcharge amount currency.'
/
comment on column rcn_host_msg.originator_refnum is 'Reference number generated by originator of operation.'
/
comment on column rcn_host_msg.network_refnum is 'Reference number incoming from external network.'
/
comment on column rcn_host_msg.acq_inst_bin is 'Acquirer BIN.'
/
comment on column rcn_host_msg.status is 'Authorization status. (Dictionary OPST).'
/
comment on column rcn_host_msg.is_reversal is 'Reversal indicator. 0 – operation is not reversal, 1 – operation is reversal.'
/
comment on column rcn_host_msg.merchant_number is 'ISO Merchant number'
/
comment on column rcn_host_msg.mcc is 'Merchant category code (MCC)'
/
comment on column rcn_host_msg.merchant_name is 'Merchant name'
/
comment on column rcn_host_msg.merchant_street is 'Merchant street'
/
comment on column rcn_host_msg.merchant_city is 'Merchant city'
/
comment on column rcn_host_msg.merchant_region is 'Merchant region'
/
comment on column rcn_host_msg.merchant_country is 'Merchant country'
/
comment on column rcn_host_msg.merchant_postcode is 'merchant postal code'
/
comment on column rcn_host_msg.terminal_type is 'Terminal type. (Dictionary TRMT).'
/
comment on column rcn_host_msg.terminal_number is 'ISO Terminal number'
/
comment on column rcn_host_msg.acq_inst_id is 'Identifier of participant acquirer.'
/
comment on column rcn_host_msg.card_mask is 'Card mask'
/
comment on column rcn_host_msg.card_seq_number is 'Card sequential number'
/
comment on column rcn_host_msg.card_expir_date is 'Card expiration date'
/
comment on column rcn_host_msg.card_country is 'Card country'
/
comment on column rcn_host_msg.iss_inst_id is 'Identifier of participant institution.'
/
comment on column rcn_host_msg.auth_code is 'Authorization code'
/
alter table rcn_host_msg modify (terminal_number varchar2(16))
/
alter table rcn_host_msg drop column sttl_type
/
alter table rcn_host_msg drop column oper_request_amount
/
alter table rcn_host_msg drop column oper_request_currency
/
alter table rcn_host_msg drop column network_refnum
/
alter table rcn_host_msg drop column acq_inst_bin
/
alter table rcn_host_msg drop column card_country
/
alter table rcn_host_msg drop column iss_inst_id
/
alter table rcn_host_msg add (oper_cashback_amount number(22, 4))
/
comment on column rcn_host_msg.oper_cashback_amount is 'Cashback amount value.'
/
alter table rcn_host_msg add (oper_cashback_currency varchar2(3))
/
comment on column rcn_host_msg.oper_cashback_currency is 'Cashback amount currency code.'
/
alter table rcn_host_msg add (service_code varchar2(12))
/
comment on column rcn_host_msg.service_code is 'Card service code (de 40).'
/
alter table rcn_host_msg add (approval_code varchar2(24))
/
comment on column rcn_host_msg.approval_code is 'Approval Code (de 38).'
/
alter table rcn_host_msg add (rrn varchar2(48))
/
comment on column rcn_host_msg.rrn is 'Retrieval Reference Number (de 37).'
/
alter table rcn_host_msg add (trn varchar2(64))
/
comment on column rcn_host_msg.trn is 'Transaction  Reference  Number (de 63). Internal identifier of a transaction (created by the sender`s system).'
/
alter table rcn_host_msg add (original_id varchar2(120))
/
comment on column rcn_host_msg.original_id is 'Internal identifier of original transaction (created by the sender`s system). Used for: h2h transactions in which does not participate IPS. Reversal transaction only. It contains reference to original transaction.'
/
alter table rcn_host_msg add (emv_5f2a number(22, 4))
/
comment on column rcn_host_msg.emv_5f2a is 'Transaction Currency Code  Tag 5F2A  Taken from terminal initialisation table or chip card.'
/
alter table rcn_host_msg add (emv_5f34 number(22, 4))
/
comment on column rcn_host_msg.emv_5f34 is 'Application Primary Account Number (PAN) Sequence Number. This field is present if it was present in the chip card.'
/
alter table rcn_host_msg add (emv_71 varchar2(64))
/
comment on column rcn_host_msg.emv_71 is 'Issuer Script Template 1  Tag 71  (Response Message) Scripts from the issuer sent to the terminal for delivery to the ICC. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_72 varchar2(64))
/
comment on column rcn_host_msg.emv_72 is 'Issuer Script Template 2  Tag 72  (Response Msg)  Scripts from the issuer sent to the terminal for delivery to the ICC. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_82 varchar2(32))
/
comment on column rcn_host_msg.emv_82 is 'Application Interchange Profile  Tag 82  Specifies the application functions that is supported by the card. The terminal attempts to execute only those functions that the ICC supports. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_84 varchar2(128))
/
comment on column rcn_host_msg.emv_84 is 'Dedicated File (DF) Name  Tag 84  Taken from the application (application specific data). Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_8a varchar2(128))
/
comment on column rcn_host_msg.emv_8a is 'Authorisation Response Code  Code that defines the disposition of a message.'
/
alter table rcn_host_msg add (emv_91 varchar2(128))
/
comment on column rcn_host_msg.emv_91 is 'Issuer Authentication Data  Tag 91  (Response Message) Sent by the issuer if on-line issuer authentication is required. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_95 varchar2(40))
/
comment on column rcn_host_msg.emv_95 is 'Terminal Verification Result (TVR)  Tag 95  Status of the different functions as seen by the terminal during the processing of a transaction. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9a number(22, 6))
/
comment on column rcn_host_msg.emv_9a is 'Transaction Date  Tag 9A  Formatted as YYMMDD. Taken from terminal clock.'
/
alter table rcn_host_msg add (emv_9c number(22, 2))
/
comment on column rcn_host_msg.emv_9c is 'Transaction Type  Tag 9C  Taken from the transaction data.'
/
alter table rcn_host_msg add (emv_9f02 number(22, 12))
/
comment on column rcn_host_msg.emv_9f02 is 'Transaction Amount  Tag 9F02  Taken from transaction data.'
/
alter table rcn_host_msg add (emv_9f03 number(22, 12))
/
comment on column rcn_host_msg.emv_9f03 is 'Amount Other-Tag 9F03.'
/
alter table rcn_host_msg add (emv_9f06 varchar2(256))
/
comment on column rcn_host_msg.emv_9f06 is 'Application Identifier (AID)  Identifies the application as described in ISO/IEC 7816-5. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f09 varchar2(16))
/
comment on column rcn_host_msg.emv_9f09 is 'Terminal Application Version Number  Tag 9F09. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f10 varchar2(256))
/
comment on column rcn_host_msg.emv_9f10 is 'Issuer Application Data (IAD) Tag 9F10. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f18 varchar2(32))
/
comment on column rcn_host_msg.emv_9f18 is 'Issuer Script Identifier  Identification of the Issuer Script. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f1a number(22, 4))
/
comment on column rcn_host_msg.emv_9f1a is 'Terminal Country Code  Tag 9F1A.'
/
alter table rcn_host_msg add (emv_9f1e varchar2(64))
/
comment on column rcn_host_msg.emv_9f1e is 'Interface Device (IFD) Serial Number-Tag 9F1E.'
/
alter table rcn_host_msg add (emv_9f26 varchar2(64))
/
comment on column rcn_host_msg.emv_9f26 is 'Application Cryptogram (AC)  Tag 9F26. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f27 varchar2(8))
/
comment on column rcn_host_msg.emv_9f27 is 'Cryptogram Information Data  Tag 9F27  Used to approve offline transactions. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f28 varchar2(64))
/
comment on column rcn_host_msg.emv_9f28 is 'Authorisation Request Cryptogram (ARQC)  Tag 9F28. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f29 varchar2(64))
/
comment on column rcn_host_msg.emv_9f29 is 'Transaction Certificate (TC)  Tag 9F29. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f33 varchar2(24))
/
comment on column rcn_host_msg.emv_9f33 is 'Terminal Capabilities  Tag 9F33  Specifies the capabilities of the terminal. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f34 varchar2(24))
/
comment on column rcn_host_msg.emv_9f34 is 'CVM Results  Tag 9F34  Result of the last cardholder verification method. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f35 number(22, 2))
/
comment on column rcn_host_msg.emv_9f35 is 'Terminal Type  Tag 9F35  Specifies the type of terminal.'
/
alter table rcn_host_msg add (emv_9f36 varchar2(128))
/
comment on column rcn_host_msg.emv_9f36 is 'Application Transaction Counter (ATC)  Tag 9F36  from the card. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f37 varchar2(128))
/
comment on column rcn_host_msg.emv_9f37 is 'Unpredictable Number-Tag 9F37  Value to provide variability and uniqueness to the generation of the application cryptogram. Type of data Hexadecimal.'
/
alter table rcn_host_msg add (emv_9f41 number(22, 8))
/
comment on column rcn_host_msg.emv_9f41 is 'Transaction Sequence Counter-Tag 9F41  Counter maintained by the terminal that is incremented by one for each transaction.'
/
alter table rcn_host_msg add (emv_9f53 varchar2(128))
/
comment on column rcn_host_msg.emv_9f53 is 'Transaction Category Code / Merchant Category Code  Tag 9F53  Usually provided by the acquirer.'
/
alter table rcn_host_msg add (pdc_1 varchar2(32))
/
comment on column rcn_host_msg.pdc_1 is 'Card data input capability. Dictionary F221 in SV.'
/
alter table rcn_host_msg add (pdc_2 varchar2(32))
/
comment on column rcn_host_msg.pdc_2 is 'Cardholder authentication capability. Dictionary F222 in SV.'
/
alter table rcn_host_msg add (pdc_3 varchar2(32))
/
comment on column rcn_host_msg.pdc_3 is 'Card capture capability. Dictionary F223 in SV.'
/
alter table rcn_host_msg add (pdc_4 varchar2(32))
/
comment on column rcn_host_msg.pdc_4 is 'Operating environment. Dictionary F224 in SV.'
/
alter table rcn_host_msg add (pdc_5 varchar2(32))
/
comment on column rcn_host_msg.pdc_5 is 'Cardholder presence indicator. Dictionary F225 in SV.'
/
alter table rcn_host_msg add (pdc_6 varchar2(32))
/
comment on column rcn_host_msg.pdc_6 is 'Card presence indicator. Dictionary F226 in SV.'
/
alter table rcn_host_msg add (pdc_7 varchar2(32))
/
comment on column rcn_host_msg.pdc_7 is 'Card data input mode. Dictionary F227 in SV.'
/
alter table rcn_host_msg add (pdc_8 varchar2(32))
/
comment on column rcn_host_msg.pdc_8 is 'Cardholder authentication method. Dictionary F228 in SV.'
/
alter table rcn_host_msg add (pdc_9 varchar2(32))
/
comment on column rcn_host_msg.pdc_9 is 'Cardholder authentication entity. Dictionary F229 in SV.'
/
alter table rcn_host_msg add (pdc_10 varchar2(32))
/
comment on column rcn_host_msg.pdc_10 is 'Card Data Output Capability.'
/
alter table rcn_host_msg add (pdc_11 varchar2(32))
/
comment on column rcn_host_msg.pdc_11 is 'Terminal output capability. Dictionary F22B in SV.'
/
alter table rcn_host_msg add (pdc_12 varchar2(32))
/
comment on column rcn_host_msg.pdc_12 is 'Pin capture capability. Dictionary F22C in SV.'
/
alter table rcn_host_msg add (forw_inst_code varchar2(12))
/
comment on column rcn_host_msg.forw_inst_code is 'Forwarding Institution code.'
/
alter table rcn_host_msg add (receiv_inst_code varchar2(12))
/
comment on column rcn_host_msg.receiv_inst_code is 'Receiving Institution code.'
/
alter table rcn_host_msg add (sttl_date date)
/
comment on column rcn_host_msg.sttl_date is 'Settlement date.'
/
alter table rcn_host_msg add (oper_reason varchar2(8))
/
comment on column rcn_host_msg.oper_reason is 'Operation reason.'
/
comment on column rcn_host_msg.originator_refnum is 'Obsolete column.'
/
comment on column rcn_host_msg.auth_code is 'Obsolete column.'
/
alter table rcn_host_msg add (arn varchar2(36))
/
comment on column rcn_host_msg.auth_code is 'Acquirer Reference Data (DE31). Reference number incoming from external network'
/
