
package ru.bpc.sv2.authorization;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FEBOInterchange", targetNamespace = "http://www.bpc.ru/sv2/authorization", wsdlLocation = "META-INF/wsdl/posting.wsdl")
public class FEBOInterchange
    extends Service
{

    private final static URL FEBOINTERCHANGE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.bpc.sv2.authorization.FEBOInterchange.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.bpc.sv2.authorization.FEBOInterchange.class.getResource(".");
            url = new URL(baseUrl, "META-INF/wsdl/posting.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/posting.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FEBOINTERCHANGE_WSDL_LOCATION = url;
    }

    public FEBOInterchange(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FEBOInterchange() {
        super(FEBOINTERCHANGE_WSDL_LOCATION, new QName("http://www.bpc.ru/sv2/authorization", "FEBOInterchange"));
    }

    /**
     * 
     * @return
     *     returns Authorization
     */
    @WebEndpoint(name = "NewPort")
    public Authorization getNewPort() {
        return super.getPort(new QName("http://www.bpc.ru/sv2/authorization", "NewPort"), Authorization.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authorization
     */
    @WebEndpoint(name = "NewPort")
    public Authorization getNewPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bpc.ru/sv2/authorization", "NewPort"), Authorization.class, features);
    }

}
