create or replace force view vis_fin_message_vw as
select v.id
     , v.status
     , v.file_id
     , v.batch_id
     , v.record_number
     , v.is_reversal
     , v.is_incoming
     , v.is_returned
     , v.is_invalid
     , v.dispute_id
     , v.rrn
     , v.inst_id
     , v.network_id
     , v.trans_code
     , v.trans_code_qualifier
     , v.card_id
     , v.card_mask
     , v.card_hash
     , v.oper_amount
     , v.oper_currency
     , v.oper_date
     , v.sttl_amount
     , v.sttl_currency
     , v.network_amount
     , v.network_currency
     , v.floor_limit_ind
     , v.exept_file_ind
     , v.pcas_ind
     , v.arn
     , v.acquirer_bin
     , v.acq_business_id
     , v.merchant_name
     , v.merchant_city
     , v.merchant_country
     , v.merchant_postal_code
     , v.merchant_region
     , v.merchant_street
     , v.mcc
     , v.req_pay_service
     , v.usage_code
     , v.reason_code
     , v.settlement_flag
     , v.auth_char_ind
     , v.auth_code
     , v.pos_terminal_cap
     , v.inter_fee_ind
     , v.crdh_id_method
     , v.collect_only_flag
     , v.pos_entry_mode
     , v.central_proc_date
     , v.reimburst_attr
     , v.iss_workst_bin
     , v.acq_workst_bin
     , v.chargeback_ref_num
     , v.docum_ind
     , v.member_msg_text
     , v.spec_cond_ind
     , v.fee_program_ind
     , v.issuer_charge
     , v.merchant_number
     , v.terminal_number
     , v.national_reimb_fee
     , v.electr_comm_ind
     , v.spec_chargeback_ind
     , v.interface_trace_num
     , v.unatt_accept_term_ind
     , v.prepaid_card_ind
     , v.service_development
     , v.avs_resp_code
     , v.auth_source_code
     , v.purch_id_format
     , v.account_selection
     , v.installment_pay_count
     , v.purch_id
     , v.cashback
     , v.chip_cond_code
     , v.pos_environment
     , v.transaction_type
     , v.card_seq_number
     , v.terminal_profile
     , v.unpredict_number
     , v.appl_trans_counter
     , v.appl_interch_profile
     , v.cryptogram
     , v.term_verif_result
     , v.cryptogram_amount
     , v.card_verif_result
     , v.issuer_appl_data
     , v.issuer_script_result
     , v.card_expir_date
     , v.cryptogram_version
     , v.cvv2_result_code
     , v.auth_resp_code
     , v.cryptogram_info_data
     , v.transaction_id
     , v.merchant_verif_value
     , v.host_inst_id
     , v.proc_bin
     , v.chargeback_reason_code
     , v.destination_channel
     , v.source_channel
     , v.acq_inst_bin
     , v.spend_qualified_ind
     , v.clearing_sequence_num
     , v.clearing_sequence_count
     , v.service_code
     , v.business_format_code
     , v.token_assurance_level
     , v.pan_token
     , v.validation_code
     , v.payment_forms_num
     , v.business_format_code_e
     , t4.agent_unique_id
     , v.additional_auth_method
     , v.additional_reason_code
     , v.product_id
     , v.auth_amount
     , v.auth_currency
     , v.form_factor_indicator
     , v.fast_funds_indicator
     , v.business_format_code_3
     , v.business_application_id
     , v.source_of_funds
     , v.payment_reversal_code
     , v.sender_reference_number
     , v.sender_account_number
     , v.sender_name
     , v.sender_address
     , v.sender_city
     , v.sender_state
     , v.sender_country
     , v.network_code
     , v.fee_interchange_amount
     , v.fee_interchange_sign
     , v.program_id
     , v.dcc_indicator
     , v.is_rejected
     , t4.trans_comp_number
     , t4.business_format_code as business_format_code_4
     , t4.contact_information
     , t4.adjustment_indicator
     , t4.message_reason_code
     , t4.dispute_condition
     , t4.vrol_financial_id
     , t4.vrol_case_number
     , t4.vrol_bundle_number
     , t4.client_case_number
     , t4.dispute_status
     , t4.surcharge_amount
     , t4.surcharge_sign
     , t4.payment_acc_ref
     , t4.token_requestor_id
     , v.terminal_country
     , t3.trans_comp_number as trans_comp_number_tcr3
     , t3.business_application_id as business_application_id_tcr3
     , t3.business_format_code as business_format_code_tcr3
     , t3.passenger_name
     , t3.departure_date
     , t3.orig_city_airport_code
     , t3.carrier_code_1
     , t3.service_class_code_1
     , t3.stop_over_code_1
     , t3.dest_city_airport_code_1
     , t3.carrier_code_2
     , t3.service_class_code_2
     , t3.stop_over_code_2
     , t3.dest_city_airport_code_2
     , t3.carrier_code_3
     , t3.service_class_code_3
     , t3.stop_over_code_3
     , t3.dest_city_airport_code_3
     , t3.carrier_code_4
     , t3.service_class_code_4
     , t3.stop_over_code_4
     , t3.dest_city_airport_code_4
     , t3.travel_agency_code
     , t3.travel_agency_name
     , t3.restrict_ticket_indicator
     , t3.fare_basis_code_1
     , t3.fare_basis_code_2
     , t3.fare_basis_code_3
     , t3.fare_basis_code_4
     , t3.comp_reserv_system
     , t3.flight_number_1
     , t3.flight_number_2
     , t3.flight_number_3
     , t3.flight_number_4
     , t3.credit_reason_indicator
     , t3.ticket_change_indicator
     , v.recipient_name
     , v.terminal_trans_date
     , v.conv_date
  from vis_fin_message v
     , vis_tcr4 t4
     , vis_tcr3 t3
 where v.id = t4.id(+)
   and v.id = t3.id(+)
/
