create or replace force view vis_fin_message_unpivot_vw as
select 
   o.id
   , x.column_id
   , x.column_name
   , x.data_type
   , (case x.column_name
        when 'status' then o.status
        when 'file_id' then to_char(o.file_id,'FM000000000000000000.0000')
        when 'batch_id' then to_char(o.batch_id,'FM000000000000000000.0000')
        when 'record_number' then to_char(o.record_number,'FM000000000000000000.0000')
        when 'is_reversal' then to_char(o.is_reversal,'FM000000000000000000.0000')
        when 'is_incoming' then to_char(o.is_incoming,'FM000000000000000000.0000')
        when 'is_returned' then to_char(o.is_returned,'FM000000000000000000.0000')
        when 'is_invalid' then to_char(o.is_invalid,'FM000000000000000000.0000')
        when 'dispute_id' then to_char(o.dispute_id,'FM000000000000000000.0000')
        when 'rrn' then o.rrn
        when 'inst_id' then to_char(o.inst_id,'FM000000000000000000.0000')
        when 'network_id' then to_char(o.network_id,'FM000000000000000000.0000')
        when 'trans_code' then o.trans_code
        when 'trans_code_qualifier' then o.trans_code_qualifier
        when 'card_id' then to_char(o.card_id,'FM000000000000000000.0000')
        when 'card_mask' then o.card_mask
        when 'card_hash' then to_char(o.card_hash,'FM000000000000000000.0000')
        when 'oper_amount' then to_char(o.oper_amount,'FM000000000000000000.0000')
        when 'oper_currency' then o.oper_currency
        when 'oper_date' then to_char(o.oper_date,'yyyymmddhh24miss')
        when 'sttl_amount' then to_char(o.sttl_amount,'FM000000000000000000.0000')
        when 'sttl_currency' then o.sttl_currency
        when 'network_amount' then to_char(o.network_amount,'FM000000000000000000.0000')
        when 'network_currency' then o.network_currency
        when 'floor_limit_ind' then o.floor_limit_ind
        when 'exept_file_ind' then o.exept_file_ind
        when 'pcas_ind' then o.pcas_ind
        when 'arn' then o.arn
        when 'acquirer_bin' then o.acquirer_bin
        when 'acq_business_id' then o.acq_business_id
        when 'merchant_name' then o.merchant_name
        when 'merchant_city' then o.merchant_city
        when 'merchant_country' then o.merchant_country
        when 'merchant_postal_code' then o.merchant_postal_code
        when 'merchant_region' then o.merchant_region
        when 'merchant_street' then o.merchant_street
        when 'mcc' then o.mcc
        when 'req_pay_service' then o.req_pay_service
        when 'usage_code' then o.usage_code
        when 'reason_code' then o.reason_code
        when 'settlement_flag' then o.settlement_flag
        when 'auth_char_ind' then o.auth_char_ind
        when 'auth_code' then o.auth_code
        when 'pos_terminal_cap' then o.pos_terminal_cap
        when 'inter_fee_ind' then o.inter_fee_ind
        when 'crdh_id_method' then o.crdh_id_method
        when 'collect_only_flag' then o.collect_only_flag
        when 'pos_entry_mode' then o.pos_entry_mode
        when 'central_proc_date' then o.central_proc_date
        when 'reimburst_attr' then o.reimburst_attr
        when 'iss_workst_bin' then o.iss_workst_bin
        when 'acq_workst_bin' then o.acq_workst_bin
        when 'chargeback_ref_num' then o.chargeback_ref_num
        when 'docum_ind' then o.docum_ind
        when 'member_msg_text' then o.member_msg_text
        when 'spec_cond_ind' then o.spec_cond_ind
        when 'fee_program_ind' then o.fee_program_ind
        when 'issuer_charge' then o.issuer_charge
        when 'merchant_number' then o.merchant_number
        when 'terminal_number' then o.terminal_number
        when 'national_reimb_fee' then o.national_reimb_fee
        when 'electr_comm_ind' then o.electr_comm_ind
        when 'spec_chargeback_ind' then o.spec_chargeback_ind
        when 'interface_trace_num' then o.interface_trace_num
        when 'unatt_accept_term_ind' then o.unatt_accept_term_ind
        when 'prepaid_card_ind' then o.prepaid_card_ind
        when 'service_development' then o.service_development
        when 'avs_resp_code' then o.avs_resp_code
        when 'auth_source_code' then o.auth_source_code
        when 'purch_id_format' then o.purch_id_format
        when 'account_selection' then o.account_selection
        when 'installment_pay_count' then o.installment_pay_count
        when 'purch_id' then o.purch_id
        when 'cashback' then o.cashback
        when 'chip_cond_code' then o.chip_cond_code
        when 'pos_environment' then o.pos_environment
        when 'transaction_type' then o.transaction_type
        when 'card_seq_number' then o.card_seq_number
        when 'terminal_profile' then o.terminal_profile
        when 'unpredict_number' then o.unpredict_number
        when 'appl_trans_counter' then o.appl_trans_counter
        when 'appl_interch_profile' then o.appl_interch_profile
        when 'cryptogram' then o.cryptogram
        when 'term_verif_result' then o.term_verif_result
        when 'cryptogram_amount' then o.cryptogram_amount
        when 'card_verif_result' then o.card_verif_result
        when 'issuer_appl_data' then o.issuer_appl_data
        when 'issuer_script_result' then o.issuer_script_result
        when 'card_expir_date' then o.card_expir_date
        when 'cryptogram_version' then o.cryptogram_version
        when 'cvv2_result_code' then o.cvv2_result_code
        when 'auth_resp_code' then o.auth_resp_code
        when 'cryptogram_info_data' then o.cryptogram_info_data
        when 'transaction_id' then o.transaction_id
        when 'merchant_verif_value' then o.merchant_verif_value
        when 'host_inst_id' then to_char(o.host_inst_id,'FM000000000000000000.0000')
        when 'proc_bin' then o.proc_bin
        when 'chargeback_reason_code' then o.chargeback_reason_code
        when 'destination_channel' then o.destination_channel
        when 'source_channel' then o.source_channel
        when 'acq_inst_bin' then o.acq_inst_bin
        when 'spend_qualified_ind' then o.spend_qualified_ind
        when 'clearing_sequence_num' then to_char(o.clearing_sequence_num,'FM000000000000000000.0000')
        when 'clearing_sequence_count' then to_char(o.clearing_sequence_count,'FM000000000000000000.0000')
        when 'service_code' then o.service_code
        when 'business_format_code' then o.business_format_code
        when 'token_assurance_level' then o.token_assurance_level
        when 'pan_token' then to_char(o.pan_token,'FM000000000000000000.0000')
        when 'validation_code' then o.validation_code
        when 'payment_forms_num' then o.payment_forms_num
        when 'business_format_code_e' then o.business_format_code_e
        when 'agent_unique_id' then o.agent_unique_id
        when 'additional_auth_method' then o.additional_auth_method
        when 'additional_reason_code' then o.additional_reason_code
        when 'product_id' then o.product_id
        when 'auth_amount' then to_char(o.auth_amount,'FM000000000000000000.0000')
        when 'auth_currency' then o.auth_currency
        when 'form_factor_indicator' then o.form_factor_indicator
        when 'fast_funds_indicator' then o.fast_funds_indicator
        when 'business_format_code_3' then o.business_format_code_3
        when 'business_application_id' then o.business_application_id
        when 'source_of_funds' then o.source_of_funds
        when 'payment_reversal_code' then o.payment_reversal_code
        when 'sender_reference_number' then o.sender_reference_number
        when 'sender_account_number' then o.sender_account_number
        when 'sender_name' then o.sender_name
        when 'sender_address' then o.sender_address
        when 'sender_city' then o.sender_city
        when 'sender_state' then o.sender_state
        when 'sender_country' then o.sender_country
        when 'network_code' then o.network_code
        when 'is_rejected' then to_char(o.is_rejected,'FM000000000000000000.0000')
        when 'fee_interchange_amount' then to_char(o.auth_amount,'FM000000000000000000.0000')
        when 'interchange_fee_sign' then to_char(o.auth_amount,'FM000000000000000000.0000')
        when 'program_id' then o.program_id
        when 'dcc_indicator' then to_char(o.auth_amount,'FM000000000000000000.0000')            
        when 'business_format_code_4' then o.business_format_code_4
        when 'contact_information' then o.contact_information
        when 'adjustment_indicator' then o.adjustment_indicator
        when 'message_reason_code' then o.message_reason_code
        when 'dispute_condition' then o.dispute_condition
        when 'vrol_financial_id' then o.vrol_financial_id
        when 'vrol_case_number' then o.vrol_case_number
        when 'vrol_bundle_number' then o.vrol_bundle_number
        when 'client_case_number' then o.client_case_number
        when 'dispute_status' then o.dispute_status
        when 'payment_acc_ref' then o.payment_acc_ref
        when 'token_requestor_id' then o.token_requestor_id
      else 'n/a'
      end) as value
 from vis_fin_message_vw o
 join (select z.column_id
            , lower(z.column_name) as column_name
            , lower(z.data_type) as data_type 
         from user_tab_columns z 
        where lower(z.table_name) = 'vis_fin_message_vw' 
          and lower(z.column_name) != 'id'
          ) x on (1=1)
/
 