create or replace force view cmp_fin_message_vw as
select
    id
  , file_id
  , inst_id
  , network_id
  , host_inst_id
  , msg_number
  , is_reversal
  , is_incoming
  , is_rejected
  , is_invalid
  , card_id
  , card_mask
  , card_hash
  , tran_code
  , conversion_rate
  , ext_stan
  , orig_time
  , capability
  , tran_type
  , tran_class
  , term_class
  , mcc
  , arn
  , ext_fid
  , tran_number
  , approval_code
  , term_name
  , term_retailer_name
  , ext_term_retailer_name
  , term_city
  , term_location
  , term_owner
  , term_country
  , term_zip
  , exp_date
  , amount
  , reconcil_amount
  , orig_amount
  , currency
  , reconcil_currency
  , orig_currency
  , pay_amount
  , pay_currency
  , term_inst_id
  , status
  , network
  , host_net_id
  , ext_tran_attr
  , term_inst_country
  , pos_condition
  , pos_entry_mode
  , pin_presence
  , term_entry_caps
  , host_time
  , ext_ps_fields
  , term_contactless_capable
  , final_rrn
  , from_acct_type
  , aid
  , orig_fi_name
  , dest_fi_name
  , clear_date
  , card_member
  , icc_term_caps
  , icc_tvr
  , icc_random
  , icc_term_sn
  , icc_issuer_data
  , icc_cryptogram
  , icc_app_tran_count
  , icc_term_tran_count
  , icc_app_profile
  , icc_iad
  , icc_tran_type
  , icc_term_country
  , icc_tran_date
  , icc_amount
  , icc_currency
  , icc_cb_amount
  , icc_crypt_inform_data
  , icc_cvm_res
  , icc_card_member
  , emv_data_exists
  , collect_only_flag
from
    cmp_fin_message
/
