//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 04:34:09 PM MSK 
//


package ru.bpc.sv2.operations.incoming.posting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for amount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amount_value" type="{http://sv2.bpc.ru/incoming/posting}money"/>
 *         &lt;element name="amount_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value"/>
 *         &lt;element name="currency" type="{http://sv2.bpc.ru/incoming/posting}currency_code"/>
 *         &lt;element name="convert_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="convert_rate" type="{http://sv2.bpc.ru/incoming/posting}money"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amount", propOrder = {
    "amountValue",
    "amountType",
    "currency",
    "convertDate",
    "convertRate"
})
public class Amount {

    @XmlElement(name = "amount_value")
    protected float amountValue;
    @XmlElement(name = "amount_type", required = true)
    protected String amountType;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(name = "convert_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar convertDate;
    @XmlElement(name = "convert_rate")
    protected float convertRate;

    /**
     * Gets the value of the amountValue property.
     * 
     */
    public float getAmountValue() {
        return amountValue;
    }

    /**
     * Sets the value of the amountValue property.
     * 
     */
    public void setAmountValue(float value) {
        this.amountValue = value;
    }

    /**
     * Gets the value of the amountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountType() {
        return amountType;
    }

    /**
     * Sets the value of the amountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountType(String value) {
        this.amountType = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the convertDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConvertDate() {
        return convertDate;
    }

    /**
     * Sets the value of the convertDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConvertDate(XMLGregorianCalendar value) {
        this.convertDate = value;
    }

    /**
     * Gets the value of the convertRate property.
     * 
     */
    public float getConvertRate() {
        return convertRate;
    }

    /**
     * Sets the value of the convertRate property.
     * 
     */
    public void setConvertRate(float value) {
        this.convertRate = value;
    }

    public boolean isOperationAmount() {
    	return "oper_amount".equalsIgnoreCase(amountType);
    }
}
