//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 04:34:09 PM MSK 
//


package ru.bpc.sv2.operations.incoming.posting;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import ru.bpc.sv2.utils.BooleanAdapter;


/**
 * <p>Java class for authorization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authorization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://sv2.bpc.ru/incoming/posting}long_id" minOccurs="0"/>
 *         &lt;element name="source_id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="original_auth_id" type="{http://sv2.bpc.ru/incoming/posting}long_id" minOccurs="0"/>
 *         &lt;element name="is_reversal" type="{http://sv2.bpc.ru/incoming/posting}bool"/>
 *         &lt;element name="msg_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value"/>
 *         &lt;element name="oper_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value"/>
 *         &lt;element name="resp_code" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="sttl_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value"/>
 *         &lt;element name="acq_inst_id" type="{http://sv2.bpc.ru/incoming/posting}tiny_id" minOccurs="0"/>
 *         &lt;element name="acq_network_id" type="{http://sv2.bpc.ru/incoming/posting}tiny_id" minOccurs="0"/>
 *         &lt;element name="terminal_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="acq_inst_bin" type="{http://sv2.bpc.ru/incoming/posting}inst_bin" minOccurs="0"/>
 *         &lt;element name="forw_inst_bin" type="{http://sv2.bpc.ru/incoming/posting}inst_bin" minOccurs="0"/>
 *         &lt;element name="merchant_id" type="{http://sv2.bpc.ru/incoming/posting}short_id" minOccurs="0"/>
 *         &lt;element name="merchant_number" type="{http://sv2.bpc.ru/incoming/posting}merchant_number" minOccurs="0"/>
 *         &lt;element name="terminal_id" type="{http://sv2.bpc.ru/incoming/posting}short_id" minOccurs="0"/>
 *         &lt;element name="terminal_number" type="{http://sv2.bpc.ru/incoming/posting}terminal_number" minOccurs="0"/>
 *         &lt;element name="merchant_name" type="{http://sv2.bpc.ru/incoming/posting}name" minOccurs="0"/>
 *         &lt;element name="merchant_street" type="{http://sv2.bpc.ru/incoming/posting}name" minOccurs="0"/>
 *         &lt;element name="merchant_city" type="{http://sv2.bpc.ru/incoming/posting}name" minOccurs="0"/>
 *         &lt;element name="merchant_region" type="{http://sv2.bpc.ru/incoming/posting}merchant_region" minOccurs="0"/>
 *         &lt;element name="merchant_country" type="{http://sv2.bpc.ru/incoming/posting}country_code" minOccurs="0"/>
 *         &lt;element name="merchant_postcode" type="{http://sv2.bpc.ru/incoming/posting}postcode" minOccurs="0"/>
 *         &lt;element name="mcc" type="{http://sv2.bpc.ru/incoming/posting}mcc" minOccurs="0"/>
 *         &lt;element name="refnum" type="{http://sv2.bpc.ru/incoming/posting}refnum" minOccurs="0"/>
 *         &lt;element name="network_refnum" type="{http://sv2.bpc.ru/incoming/posting}refnum" minOccurs="0"/>
 *         &lt;element name="card_data_input_cap" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="crdh_auth_cap" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="card_capture_cap" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="terminal_operating_env" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="crdh_presence" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="card_presence" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="card_data_input_mode" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="crdh_auth_method" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="crdh_auth_entity" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="card_data_output_cap" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="terminal_output_cap" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="pin_capture_cap" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="pin_presence" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="cvc_indicator" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="cat_level" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="pos_entry_mod" type="{http://sv2.bpc.ru/incoming/posting}pos_entry_mod" minOccurs="0"/>
 *         &lt;element name="pos_cond_code" type="{http://sv2.bpc.ru/incoming/posting}pos_cond_code" minOccurs="0"/>
 *         &lt;element name="service_provider_id" type="{http://sv2.bpc.ru/incoming/posting}short_id" minOccurs="0"/>
 *         &lt;element name="service_id" type="{http://sv2.bpc.ru/incoming/posting}short_id" minOccurs="0"/>
 *         &lt;element name="emv_data" type="{http://sv2.bpc.ru/incoming/posting}description" minOccurs="0"/>
 *         &lt;element name="auth_code" type="{http://sv2.bpc.ru/incoming/posting}auth_code" minOccurs="0"/>
 *         &lt;element name="amount" type="{http://sv2.bpc.ru/incoming/posting}amount" maxOccurs="unbounded"/>
 *         &lt;element name="oper_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="host_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="iss_inst_id" type="{http://sv2.bpc.ru/incoming/posting}tiny_id" minOccurs="0"/>
 *         &lt;element name="iss_network_id" type="{http://sv2.bpc.ru/incoming/posting}tiny_id" minOccurs="0"/>
 *         &lt;element name="card_inst_id" type="{http://sv2.bpc.ru/incoming/posting}tiny_id" minOccurs="0"/>
 *         &lt;element name="card_network_id" type="{http://sv2.bpc.ru/incoming/posting}tiny_id" minOccurs="0"/>
 *         &lt;element name="card" type="{http://sv2.bpc.ru/incoming/posting}card" minOccurs="0"/>
 *         &lt;element name="account_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="account_number" type="{http://sv2.bpc.ru/incoming/posting}account_number" minOccurs="0"/>
 *         &lt;element name="client_ident_type" type="{http://sv2.bpc.ru/incoming/posting}dict_value" minOccurs="0"/>
 *         &lt;element name="is_advice" type="{http://sv2.bpc.ru/incoming/posting}bool" minOccurs="0"/>
 *         &lt;element name="is_repeat" type="{http://sv2.bpc.ru/incoming/posting}bool" minOccurs="0"/>
 *         &lt;element name="is_completed" type="{http://sv2.bpc.ru/incoming/posting}bool" minOccurs="0"/>
 *         &lt;element name="addl_data" type="{http://sv2.bpc.ru/incoming/posting}description" minOccurs="0"/>
 *         &lt;element name="oper_count" type="{http://sv2.bpc.ru/incoming/posting}short_id" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authorization", propOrder = {
    "id",
    "sourceId",
    "originalAuthId",
    "reversal",
    "msgType",
    "operType",
    "respCode",
    "sttlType",
    "acqInstId",
    "acqNetworkId",
    "terminalType",
    "acqInstBin",
    "forwInstBin",
    "merchantId",
    "merchantNumber",
    "terminalId",
    "terminalNumber",
    "merchantName",
    "merchantStreet",
    "merchantCity",
    "merchantRegion",
    "merchantCountry",
    "merchantPostcode",
    "mcc",
    "refnum",
    "networkRefnum",
    "cardDataInputCap",
    "crdhAuthCap",
    "cardCaptureCap",
    "terminalOperatingEnv",
    "crdhPresence",
    "cardPresence",
    "cardDataInputMode",
    "crdhAuthMethod",
    "crdhAuthEntity",
    "cardDataOutputCap",
    "terminalOutputCap",
    "pinCaptureCap",
    "pinPresence",
    "cvcIndicator",
    "catLevel",
    "posEntryMod",
    "posCondCode",
    "serviceProviderId",
    "serviceId",
    "emvData",
    "authCode",
    "amount",
    "operDate",
    "hostDate",
    "issInstId",
    "issNetworkId",
    "cardInstId",
    "cardNetworkId",
    "card",
    "accountType",
    "accountNumber",
    "clientIdentType",
    "isAdvice",
    "isRepeat",
    "isCompleted",
    "addlData",
    "operCount",
    "status",
    "matchStatus"
})
public class Authorization {

    protected Integer id;
    @XmlElement(name = "source_id")
    protected Integer sourceId;
    @XmlElement(name = "original_auth_id")
    protected Integer originalAuthId;
    @XmlElement(name = "is_reversal")
    @XmlJavaTypeAdapter( BooleanAdapter.class )
    protected Boolean reversal;
    @XmlElement(name = "msg_type", required = true)
    protected String msgType;
    @XmlElement(name = "oper_type", required = true)
    protected String operType;
    @XmlElement(name = "resp_code")
    protected String respCode;
    @XmlElement(name = "sttl_type", required = true)
    protected String sttlType;
    @XmlElement(name = "acq_inst_id")
    protected Integer acqInstId;
    @XmlElement(name = "acq_network_id")
    protected Integer acqNetworkId;
    @XmlElement(name = "terminal_type")
    protected String terminalType;
    @XmlElement(name = "acq_inst_bin")
    protected String acqInstBin;
    @XmlElement(name = "forw_inst_bin")
    protected String forwInstBin;
    @XmlElement(name = "merchant_id")
    protected Integer merchantId;
    @XmlElement(name = "merchant_number")
    protected String merchantNumber;
    @XmlElement(name = "terminal_id")
    protected Integer terminalId;
    @XmlElement(name = "terminal_number")
    protected String terminalNumber;
    @XmlElement(name = "merchant_name")
    protected String merchantName;
    @XmlElement(name = "merchant_street")
    protected String merchantStreet;
    @XmlElement(name = "merchant_city")
    protected String merchantCity;
    @XmlElement(name = "merchant_region")
    protected String merchantRegion;
    @XmlElement(name = "merchant_country")
    protected String merchantCountry;
    @XmlElement(name = "merchant_postcode")
    protected String merchantPostcode;
    protected String mcc;
    protected String refnum;
    @XmlElement(name = "network_refnum")
    protected String networkRefnum;
    @XmlElement(name = "card_data_input_cap")
    protected String cardDataInputCap;
    @XmlElement(name = "crdh_auth_cap")
    protected String crdhAuthCap;
    @XmlElement(name = "card_capture_cap")
    protected String cardCaptureCap;
    @XmlElement(name = "terminal_operating_env")
    protected String terminalOperatingEnv;
    @XmlElement(name = "crdh_presence")
    protected String crdhPresence;
    @XmlElement(name = "card_presence")
    protected String cardPresence;
    @XmlElement(name = "card_data_input_mode")
    protected String cardDataInputMode;
    @XmlElement(name = "crdh_auth_method")
    protected String crdhAuthMethod;
    @XmlElement(name = "crdh_auth_entity")
    protected String crdhAuthEntity;
    @XmlElement(name = "card_data_output_cap")
    protected String cardDataOutputCap;
    @XmlElement(name = "terminal_output_cap")
    protected String terminalOutputCap;
    @XmlElement(name = "pin_capture_cap")
    protected String pinCaptureCap;
    @XmlElement(name = "pin_presence")
    protected String pinPresence;
    @XmlElement(name = "cvc_indicator")
    protected String cvcIndicator;
    @XmlElement(name = "cat_level")
    protected String catLevel;
    @XmlElement(name = "pos_entry_mod")
    protected String posEntryMod;
    @XmlElement(name = "pos_cond_code")
    protected String posCondCode;
    @XmlElement(name = "service_provider_id")
    protected Integer serviceProviderId;
    @XmlElement(name = "service_id")
    protected Integer serviceId;
    @XmlElement(name = "emv_data")
    protected String emvData;
    @XmlElement(name = "auth_code")
    protected String authCode;
    @XmlElement(required = true)
    protected List<Amount> amount;
    @XmlElement(name = "oper_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operDate;
    @XmlElement(name = "host_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar hostDate;
    @XmlElement(name = "iss_inst_id")
    protected Integer issInstId;
    @XmlElement(name = "iss_network_id")
    protected Integer issNetworkId;
    @XmlElement(name = "card_inst_id")
    protected Integer cardInstId;
    @XmlElement(name = "card_network_id")
    protected Integer cardNetworkId;
    protected Card card;
    @XmlElement(name = "account_type")
    protected String accountType;
    @XmlElement(name = "account_number")
    protected String accountNumber;
    @XmlElement(name = "client_ident_type")
    protected String clientIdentType;
    @XmlElement(name = "is_advice")
    protected Integer isAdvice;
    @XmlElement(name = "is_repeat")
    protected Integer isRepeat;
    @XmlElement(name = "is_completed")
    protected Integer isCompleted;
    @XmlElement(name = "addl_data")
    protected String addlData;
    @XmlElement(name = "oper_count")
    protected Integer operCount;
    
    @XmlElement(name = "status")
    protected String status;
    
    @XmlElement(name = "match_status")
    protected String matchStatus;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the sourceId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSourceId(Integer value) {
        this.sourceId = value;
    }

    /**
     * Gets the value of the originalAuthId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOriginalAuthId() {
        return originalAuthId;
    }

    /**
     * Sets the value of the originalAuthId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOriginalAuthId(Integer value) {
        this.originalAuthId = value;
    }

    /**
     * Gets the value of the isReversal property.
     * 
     */
    public Boolean isReversal() {
        return reversal;
    }

    /**
     * Sets the value of the isReversal property.
     * 
     */
    public void setReversal(Boolean value) {
        this.reversal = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the operType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperType() {
        return operType;
    }

    /**
     * Sets the value of the operType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperType(String value) {
        this.operType = value;
    }

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the sttlType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSttlType() {
        return sttlType;
    }

    /**
     * Sets the value of the sttlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSttlType(String value) {
        this.sttlType = value;
    }

    /**
     * Gets the value of the acqInstId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAcqInstId() {
        return acqInstId;
    }

    /**
     * Sets the value of the acqInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAcqInstId(Integer value) {
        this.acqInstId = value;
    }

    /**
     * Gets the value of the acqNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAcqNetworkId() {
        return acqNetworkId;
    }

    /**
     * Sets the value of the acqNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAcqNetworkId(Integer value) {
        this.acqNetworkId = value;
    }

    /**
     * Gets the value of the terminalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalType() {
        return terminalType;
    }

    /**
     * Sets the value of the terminalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalType(String value) {
        this.terminalType = value;
    }

    /**
     * Gets the value of the acqInstBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcqInstBin() {
        return acqInstBin;
    }

    /**
     * Sets the value of the acqInstBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcqInstBin(String value) {
        this.acqInstBin = value;
    }

    /**
     * Gets the value of the forwInstBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwInstBin() {
        return forwInstBin;
    }

    /**
     * Sets the value of the forwInstBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwInstBin(String value) {
        this.forwInstBin = value;
    }

    /**
     * Gets the value of the merchantId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMerchantId(Integer value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the merchantNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantNumber() {
        return merchantNumber;
    }

    /**
     * Sets the value of the merchantNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantNumber(String value) {
        this.merchantNumber = value;
    }

    /**
     * Gets the value of the terminalId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * Sets the value of the terminalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTerminalId(Integer value) {
        this.terminalId = value;
    }

    /**
     * Gets the value of the terminalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalNumber() {
        return terminalNumber;
    }

    /**
     * Sets the value of the terminalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalNumber(String value) {
        this.terminalNumber = value;
    }

    /**
     * Gets the value of the merchantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the value of the merchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantName(String value) {
        this.merchantName = value;
    }

    /**
     * Gets the value of the merchantStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantStreet() {
        return merchantStreet;
    }

    /**
     * Sets the value of the merchantStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantStreet(String value) {
        this.merchantStreet = value;
    }

    /**
     * Gets the value of the merchantCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCity() {
        return merchantCity;
    }

    /**
     * Sets the value of the merchantCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCity(String value) {
        this.merchantCity = value;
    }

    /**
     * Gets the value of the merchantRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantRegion() {
        return merchantRegion;
    }

    /**
     * Sets the value of the merchantRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantRegion(String value) {
        this.merchantRegion = value;
    }

    /**
     * Gets the value of the merchantCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCountry() {
        return merchantCountry;
    }

    /**
     * Sets the value of the merchantCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCountry(String value) {
        this.merchantCountry = value;
    }

    /**
     * Gets the value of the merchantPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantPostcode() {
        return merchantPostcode;
    }

    /**
     * Sets the value of the merchantPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantPostcode(String value) {
        this.merchantPostcode = value;
    }

    /**
     * Gets the value of the mcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcc() {
        return mcc;
    }

    /**
     * Sets the value of the mcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcc(String value) {
        this.mcc = value;
    }

    /**
     * Gets the value of the refnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefnum() {
        return refnum;
    }

    /**
     * Sets the value of the refnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefnum(String value) {
        this.refnum = value;
    }

    /**
     * Gets the value of the networkRefnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkRefnum() {
        return networkRefnum;
    }

    /**
     * Sets the value of the networkRefnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkRefnum(String value) {
        this.networkRefnum = value;
    }

    /**
     * Gets the value of the cardDataInputCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDataInputCap() {
        return cardDataInputCap;
    }

    /**
     * Sets the value of the cardDataInputCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDataInputCap(String value) {
        this.cardDataInputCap = value;
    }

    /**
     * Gets the value of the crdhAuthCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrdhAuthCap() {
        return crdhAuthCap;
    }

    /**
     * Sets the value of the crdhAuthCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrdhAuthCap(String value) {
        this.crdhAuthCap = value;
    }

    /**
     * Gets the value of the cardCaptureCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCaptureCap() {
        return cardCaptureCap;
    }

    /**
     * Sets the value of the cardCaptureCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCaptureCap(String value) {
        this.cardCaptureCap = value;
    }

    /**
     * Gets the value of the terminalOperatingEnv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalOperatingEnv() {
        return terminalOperatingEnv;
    }

    /**
     * Sets the value of the terminalOperatingEnv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalOperatingEnv(String value) {
        this.terminalOperatingEnv = value;
    }

    /**
     * Gets the value of the crdhPresence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrdhPresence() {
        return crdhPresence;
    }

    /**
     * Sets the value of the crdhPresence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrdhPresence(String value) {
        this.crdhPresence = value;
    }

    /**
     * Gets the value of the cardPresence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPresence() {
        return cardPresence;
    }

    /**
     * Sets the value of the cardPresence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPresence(String value) {
        this.cardPresence = value;
    }

    /**
     * Gets the value of the cardDataInputMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDataInputMode() {
        return cardDataInputMode;
    }

    /**
     * Sets the value of the cardDataInputMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDataInputMode(String value) {
        this.cardDataInputMode = value;
    }

    /**
     * Gets the value of the crdhAuthMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrdhAuthMethod() {
        return crdhAuthMethod;
    }

    /**
     * Sets the value of the crdhAuthMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrdhAuthMethod(String value) {
        this.crdhAuthMethod = value;
    }

    /**
     * Gets the value of the crdhAuthEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrdhAuthEntity() {
        return crdhAuthEntity;
    }

    /**
     * Sets the value of the crdhAuthEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrdhAuthEntity(String value) {
        this.crdhAuthEntity = value;
    }

    /**
     * Gets the value of the cardDataOutputCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDataOutputCap() {
        return cardDataOutputCap;
    }

    /**
     * Sets the value of the cardDataOutputCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDataOutputCap(String value) {
        this.cardDataOutputCap = value;
    }

    /**
     * Gets the value of the terminalOutputCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalOutputCap() {
        return terminalOutputCap;
    }

    /**
     * Sets the value of the terminalOutputCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalOutputCap(String value) {
        this.terminalOutputCap = value;
    }

    /**
     * Gets the value of the pinCaptureCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinCaptureCap() {
        return pinCaptureCap;
    }

    /**
     * Sets the value of the pinCaptureCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinCaptureCap(String value) {
        this.pinCaptureCap = value;
    }

    /**
     * Gets the value of the pinPresence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinPresence() {
        return pinPresence;
    }

    /**
     * Sets the value of the pinPresence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinPresence(String value) {
        this.pinPresence = value;
    }

    /**
     * Gets the value of the cvcIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvcIndicator() {
        return cvcIndicator;
    }

    /**
     * Sets the value of the cvcIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvcIndicator(String value) {
        this.cvcIndicator = value;
    }

    /**
     * Gets the value of the catLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatLevel() {
        return catLevel;
    }

    /**
     * Sets the value of the catLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatLevel(String value) {
        this.catLevel = value;
    }

    /**
     * Gets the value of the posEntryMod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosEntryMod() {
        return posEntryMod;
    }

    /**
     * Sets the value of the posEntryMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosEntryMod(String value) {
        this.posEntryMod = value;
    }

    /**
     * Gets the value of the posCondCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosCondCode() {
        return posCondCode;
    }

    /**
     * Sets the value of the posCondCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosCondCode(String value) {
        this.posCondCode = value;
    }

    /**
     * Gets the value of the serviceProviderId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceProviderId() {
        return serviceProviderId;
    }

    /**
     * Sets the value of the serviceProviderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceProviderId(Integer value) {
        this.serviceProviderId = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceId(Integer value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the emvData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmvData() {
        return emvData;
    }

    /**
     * Sets the value of the emvData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmvData(String value) {
        this.emvData = value;
    }

    /**
     * Gets the value of the authCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the amount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Amount }
     * 
     * 
     */
    public List<Amount> getAmount() {
        if (amount == null) {
            amount = new ArrayList<Amount>();
        }
        return this.amount;
    }

    /**
     * Gets the value of the operDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperDate() {
        return operDate;
    }

    /**
     * Sets the value of the operDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperDate(XMLGregorianCalendar value) {
        this.operDate = value;
    }

    /**
     * Gets the value of the hostDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHostDate() {
        return hostDate;
    }

    /**
     * Sets the value of the hostDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHostDate(XMLGregorianCalendar value) {
        this.hostDate = value;
    }

    /**
     * Gets the value of the issInstId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIssInstId() {
        return issInstId;
    }

    /**
     * Sets the value of the issInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIssInstId(Integer value) {
        this.issInstId = value;
    }

    /**
     * Gets the value of the issNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIssNetworkId() {
        return issNetworkId;
    }

    /**
     * Sets the value of the issNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIssNetworkId(Integer value) {
        this.issNetworkId = value;
    }

    /**
     * Gets the value of the cardInstId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCardInstId() {
        return cardInstId;
    }

    /**
     * Sets the value of the cardInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCardInstId(Integer value) {
        this.cardInstId = value;
    }

    /**
     * Gets the value of the cardNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCardNetworkId() {
        return cardNetworkId;
    }

    /**
     * Sets the value of the cardNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCardNetworkId(Integer value) {
        this.cardNetworkId = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link Card }
     *     
     */
    public Card getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link Card }
     *     
     */
    public void setCard(Card value) {
        this.card = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the clientIdentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientIdentType() {
        return clientIdentType;
    }

    /**
     * Sets the value of the clientIdentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientIdentType(String value) {
        this.clientIdentType = value;
    }

    /**
     * Gets the value of the isAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIsAdvice() {
        return isAdvice;
    }

    /**
     * Sets the value of the isAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIsAdvice(Integer value) {
        this.isAdvice = value;
    }

    /**
     * Gets the value of the isRepeat property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIsRepeat() {
        return isRepeat;
    }

    /**
     * Sets the value of the isRepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIsRepeat(Integer value) {
        this.isRepeat = value;
    }

    /**
     * Gets the value of the isCompleted property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIsCompleted() {
        return isCompleted;
    }

    /**
     * Sets the value of the isCompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIsCompleted(Integer value) {
        this.isCompleted = value;
    }

    /**
     * Gets the value of the addlData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddlData() {
        return addlData;
    }

    /**
     * Sets the value of the addlData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddlData(String value) {
        this.addlData = value;
    }

    /**
     * Gets the value of the operCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOperCount() {
        return operCount;
    }

    /**
     * Sets the value of the operCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOperCount(Integer value) {
        this.operCount = value;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMatchStatus() {
		return matchStatus;
	}

	public void setMatchStatus(String matchStatus) {
		this.matchStatus = matchStatus;
	}

}
