//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 04:34:09 PM MSK 
//


package ru.bpc.sv2.operations.incoming.posting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for card complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="card">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="card_number" type="{http://sv2.bpc.ru/incoming/posting}card_number"/>
 *         &lt;element name="card_seq_number" type="{http://sv2.bpc.ru/incoming/posting}tiny_id"/>
 *         &lt;element name="card_expir_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="card_service_code" type="{http://sv2.bpc.ru/incoming/posting}card_service_code"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "card", propOrder = {
    "cardNumber",
    "cardSeqNumber",
    "cardExpirDate",
    "cardServiceCode"
})
public class Card {

    @XmlElement(name = "card_number", required = true)
    protected String cardNumber;
    @XmlElement(name = "card_seq_number")
    protected Integer cardSeqNumber;
    @XmlElement(name = "card_expir_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cardExpirDate;
    @XmlElement(name = "card_service_code", required = true)
    protected String cardServiceCode;

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the cardSeqNumber property.
     * 
     */
    public Integer getCardSeqNumber() {
        return cardSeqNumber;
    }

    /**
     * Sets the value of the cardSeqNumber property.
     * 
     */
    public void setCardSeqNumber(int value) {
        this.cardSeqNumber = value;
    }

    /**
     * Gets the value of the cardExpirDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardExpirDate() {
        return cardExpirDate;
    }

    /**
     * Sets the value of the cardExpirDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardExpirDate(XMLGregorianCalendar value) {
        this.cardExpirDate = value;
    }

    /**
     * Gets the value of the cardServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardServiceCode() {
        return cardServiceCode;
    }

    /**
     * Sets the value of the cardServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardServiceCode(String value) {
        this.cardServiceCode = value;
    }

}
