//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 04:34:09 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sv2.bpc.ru/incoming/posting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.bpc.sv2.operations.incoming.posting;
