create table qrz_simprop_triggers(          
    sched_name          varchar(120)
  , trigger_name        varchar(200)
  , trigger_group       varchar(200)
  , str_prop_1          varchar(512)
  , str_prop_2          varchar(512)
  , str_prop_3          varchar(512)
  , int_prop_1          number(10)
  , int_prop_2          number(10)
  , long_prop_1         number(13)
  , long_prop_2         number(13)
  , dec_prop_1          numeric(13,4)
  , dec_prop_2          numeric(13,4)
  , bool_prop_1         varchar(1)
  , bool_prop_2         varchar(1)
)
/