create table opr_match_data (
    id                         number(16)
  , row_id                     varchar2(200)
  , is_reversal                number(1)
  , oper_type                  varchar2(8)
  , msg_type                   varchar2(8)
  , status                     varchar2(8)
  , acq_inst_bin               varchar2(12)
  , forw_inst_bin              varchar2(12)
  , merchant_number            varchar2(15)
  , terminal_number            varchar2(16)
  , mcc                        varchar2(4)
  , originator_refnum          varchar2(36)
  , oper_amount                number(22, 4)
  , oper_currency              varchar2(3)
  , oper_date                  date
  , clearing_sequence_num      number(2)
  , clearing_sequence_count    number(2)
  , sttl_date                  date
  , total_amount               number(22, 4)
  , split_hash                 number(4)
  , client_id_type             varchar2(8)
  , auth_code                  varchar2(6)
  , card_id                    number(12)
  , account_id                 number(12)
)
/
comment on table opr_match_data is 'Temporary table with data for matching (without any indexes for best performance)'
/
comment on column opr_match_data.id                      is 'Operation identifier'
/
comment on column opr_match_data.row_id                  is 'Row id for matching'
/
comment on column opr_match_data.is_reversal             is 'Reversal indicator'
/
comment on column opr_match_data.oper_type               is 'Operation type (OPTP dictionary)'
/
comment on column opr_match_data.msg_type                is 'Message type (MSGT dictionary)'
/
comment on column opr_match_data.status                  is 'Operation status (OPST dictionary)'
/
comment on column opr_match_data.acq_inst_bin            is 'Acquirer institution BIN'
/
comment on column opr_match_data.forw_inst_bin           is 'Forwarding institution BIN'
/
comment on column opr_match_data.merchant_number         is 'ISO Merchant number'
/
comment on column opr_match_data.terminal_number         is 'ISO Terminal number'
/
comment on column opr_match_data.mcc                     is 'Merchant category code (MCC)'
/
comment on column opr_match_data.originator_refnum       is 'Reference number generated by originator of operation'
/
comment on column opr_match_data.oper_amount             is 'Operation amount in operation currency'
/
comment on column opr_match_data.oper_currency           is 'Operation currency'
/
comment on column opr_match_data.oper_date               is 'Operation date (local device date)'
/
comment on column opr_match_data.clearing_sequence_num   is 'Multiple Clearing Sequence Number'
/
comment on column opr_match_data.clearing_sequence_count is 'Multiple Clearing Sequence Count'
/
comment on column opr_match_data.sttl_date               is 'Settlement date'
/
comment on column opr_match_data.total_amount            is 'Total amount of Incremental Preauthorization Transactions'
/
comment on column opr_match_data.split_hash              is 'Hash value to split further processing'
/
comment on column opr_match_data.client_id_type          is 'Type of client identification'
/
comment on column opr_match_data.auth_code               is 'Authorization code'
/
comment on column opr_match_data.card_id                 is 'Card identifier'
/
comment on column opr_match_data.account_id              is 'Account identifier involved in operation'
/
drop table opr_match_data
/
