create or replace type opr_operation_tpr as object (
    id                          number(16)
  , split_hash                  number(4)
  , session_id                  number(16)
  , is_reversal                 number(1)
  , original_id                 number(16)
  , oper_type                   varchar2(8)
  , oper_reason                 varchar2(8)
  , msg_type                    varchar2(8)
  , status                      varchar2(8)
  , status_reason               varchar2(8)
  , sttl_type                   varchar2(8)
  , acq_inst_id                 number(4)
  , acq_network_id              number(4)
  , split_hash_acq              number(4)
  , terminal_type               varchar2(8)
  , acq_inst_bin                varchar2(12)
  , forw_inst_bin               varchar2(12)
  , merchant_id                 number(8)
  , merchant_number             varchar2(15)
  , terminal_id                 number(8)
  , terminal_number             varchar2(8)
  , merchant_name               varchar2(200)
  , merchant_street             varchar2(200)
  , merchant_city               varchar2(200)
  , merchant_region             varchar2(3)
  , merchant_country            varchar2(3)
  , merchant_postcode           varchar2(10)
  , mcc                         varchar2(4)
  , refnum                      varchar2(12)
  , network_refnum              varchar2(12)
  , auth_code                   varchar2(6)
  , oper_request_amount         number(22,4)
  , oper_amount                 number(22,4)
  , oper_count                  number(16)
  , oper_currency               varchar2(3)
  , oper_cashback_amount        number(22,4)
  , oper_replacement_amount     number(22,4)
  , oper_surcharge_amount       number(22,4)
  , oper_date                   date
  , sttl_date                   date
  , host_date                   date
  , iss_inst_id                 number(4)
  , iss_network_id              number(4)
  , split_hash_iss              number(4)
  , card_inst_id                number(4)
  , card_network_id             number(4)
  , card_number                 varchar2(19)
  , card_id                     number(12)
  , card_type_id                number(4)
  , card_mask                   varchar2(19)
  , card_hash                   number(12)
  , card_seq_number             number(4)
  , card_expir_date             date
  , card_country                varchar2(3)
  , account_type                varchar2(8)
  , account_number              varchar2(32)
  , account_amount              number(22,4)
  , account_currency            varchar2(3)
  , match_status                varchar2(8)
  , auth_id                     number(16)
  , sttl_amount                 number(22,4)
  , sttl_currency               varchar2(3)
  , dispute_id                  number(16)
)
/
alter type opr_operation_tpr modify attribute terminal_number varchar2(16) cascade
/
