create or replace force view h2h_fin_message_vw as
select f.id
     , f.part_key
     , f.split_hash
     , f.status
     , f.inst_id
     , f.network_id
     , f.file_id
     , f.file_type
     , f.file_date
     , f.is_incoming
     , f.is_reversal
     , f.is_collection_only
     , f.is_rejected
     , f.reject_id
     , f.dispute_id
     , f.forw_inst_code
     , f.receiv_inst_code
     , f.oper_type
     , f.msg_type
     , f.oper_date
     , f.oper_amount_value
     , f.oper_amount_currency
     , f.oper_surcharge_amount_value
     , f.oper_surcharge_amount_currency
     , f.oper_cashback_amount_value
     , f.oper_cashback_amount_currency
     , f.sttl_amount_value
     , f.sttl_amount_currency
     , f.sttl_rate
     , f.crdh_bill_amount_value
     , f.crdh_bill_amount_currency
     , f.crdh_bill_rate
     , f.acq_inst_bin
     , f.arn
     , f.merchant_number
     , f.mcc
     , f.merchant_name
     , f.merchant_street
     , f.merchant_city
     , f.merchant_region
     , f.merchant_country
     , f.merchant_postcode
     , f.terminal_type
     , f.terminal_number
     , iss_api_token_pkg.decode_card_number(i_card_number => c.card_number) as card_number
     , f.card_seq_num
     , f.card_expiry
     , f.service_code
     , f.approval_code
     , f.rrn
     , f.trn
     , f.oper_id
     , f.original_id
     , f.emv_5f2a
     , f.emv_5f34
     , f.emv_71
     , f.emv_72
     , f.emv_82
     , f.emv_84
     , f.emv_8a
     , f.emv_91
     , f.emv_95
     , f.emv_9a
     , f.emv_9c
     , f.emv_9f02
     , f.emv_9f03
     , f.emv_9f06
     , f.emv_9f09
     , f.emv_9f10
     , f.emv_9f18
     , f.emv_9f1a
     , f.emv_9f1e
     , f.emv_9f26
     , f.emv_9f27
     , f.emv_9f28
     , f.emv_9f29
     , f.emv_9f33
     , f.emv_9f34
     , f.emv_9f35
     , f.emv_9f36
     , f.emv_9f37
     , f.emv_9f41
     , f.emv_9f53
     , f.pdc_1
     , f.pdc_2
     , f.pdc_3
     , f.pdc_4
     , f.pdc_5
     , f.pdc_6
     , f.pdc_7
     , f.pdc_8
     , f.pdc_9
     , f.pdc_10
     , f.pdc_11
     , f.pdc_12
  from      h2h_fin_message f
  left join h2h_card        c    on c.id = f.id
/
