insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (310, NULL, 'select dict||code as code, name as name from com_ui_dictionary_all_vw where dict = ''ENTT'' and code in (''INST'',''AGNT'', ''SRVP'') and lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (246, 'MOLR', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (101, NULL, 'select dict||code code, name from com_ui_dictionary_vw where dict = ''PRDT'' and lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (102, NULL, 'select dict||code code, name from com_ui_dictionary_vw where dict = ''ENTT'' and lang = com_ui_user_env_pkg.get_user_lang and code in (''CNTR'', ''CUST'', ''CARD'', ''ACCT'')', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (103, NULL, 'select dict||code code, name from com_ui_dictionary_vw where dict = ''ENTT'' and lang = com_ui_user_env_pkg.get_user_lang and code in (''CNTR'', ''CUST'', ''MRCH'', ''TRMN'', ''ACCT'')', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (108, 'SRVS', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (112, NULL, 'select dict||code code, name from com_ui_dictionary_vw where dict = ''ENTT'' and lang = com_ui_user_env_pkg.get_user_lang and code in (''CNTR'', ''INST'', ''ACCT'')', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (56, NULL, 'select dict || code code, name from com_ui_dictionary_vw where dict in (''ENTT'', ''DTTP'') and ((dict = ''ENTT'' and code in (''FEES'', ''CYCL'', ''LIMT'', ''AGRP'')) or dict = ''DTTP'') and lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (133, NULL, 'select a.id code, a.label name, b.entity_type, s.id service from prd_ui_attribute_vw a, prd_ui_service_type_vw b, prd_ui_service_vw s where a.definition_level in (''SADLOBJT'', ''SADLPRDT'') and (a.entity_type != ''ENTTAGRP'' or a.entity_type is null) and a.lang = com_ui_user_env_pkg.get_user_lang and a.lang = b.lang and a.service_type_id = b.id and b.lang = s.lang and s.service_type_id = b.id and a.is_cyclic = 0 and a.is_use_limit = 0', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (154, NULL, 'select distinct dict||code as code, name, lang, t.customer_entity_type, t.product_type from com_ui_dictionary_vw d, prd_contract_type_vw t where d.dict = ''CNTP'' and t.contract_type = d.dict||code and d.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 1)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (1025, 'CCTG', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (169, NULL, 'select dict||code code, name from com_ui_dictionary_vw where dict = ''ENTT'' and lang = com_ui_user_env_pkg.get_user_lang and code in (''INST'', ''CUST'', ''CARD'', ''MRCH'', ''TRMN'', ''ACCT'')', 'PRD', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (170, NULL, 'select distinct d.dict || d.code code, d.name from com_ui_dictionary_vw d where d.dict = ''ENTT'' and d.code in (''PERS'',''COMP'', ''AGNT'' , ''UNDF'') and d.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (182, NULL, 'select id code, label name, inst_id institution_id from prd_ui_service_vw where lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (215, 'RSCB', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (245, 'CRDR', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (247, 'MLRS', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (283, NULL, 'select p.id code, s.label name, p.product_id from prd_ui_product_service_vw p, prd_ui_service_vw s where s.id = p.service_id connect by prior p.id = p.parent_id and s.lang = com_ui_user_env_pkg.get_user_lang start with p.parent_id is null and s.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (284, NULL, 'select s.id code, s.label name, x.product_id from (select p.id product_id, s.id service_id from prd_product_vw p, prd_service_vw s minus select p.product_id, p.service_id from prd_product_service_vw p) x, prd_ui_service_vw s where s.status = ''SRVS0001'' and x.service_id = s.id and s.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (291, 'CTST', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (304, 'CNTP', NULL, 'PRD', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (305, NULL, 'select d.dict || d.code code, d.name from com_ui_dictionary_vw d where d.dict = ''ENTT'' and d.code in (''PERS'',''COMP'', ''UNDF'') and d.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (311, NULL, 'select code, name, customer_ext_type from (select id code, name, ''ENTTINST'' customer_ext_type, lang from ost_ui_institution_vw union all select id code, name, ''ENTTAGNT'' customer_ext_type, lang from ost_ui_agent_vw union all select id code, label name, ''ENTTSRVP'' customer_ext_type, lang from pmo_ui_provider_vw) where lang = com_ui_user_env_pkg.get_user_lang', 'APP', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (318, NULL, 'select distinct dict||code as code, name, t.product_type from com_ui_dictionary_vw d, prd_contract_type_vw t where d.dict = ''CNTP'' and t.contract_type = d.dict||code and d.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPNMCD', 'DTTPCHAR', 1)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (319, NULL, 'select d.dict || d.code code, d.name, x.product_type from com_ui_dictionary_vw d,(select ''ENTTAGNT'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTINST'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTCARD'' entity_type, ''PRDT0100'' product_type from dual union all  select ''ENTTCNTC'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTCUST'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTMRCH'' entity_type, ''PRDT0200'' product_type from dual union all select ''ENTTTRMN'' entity_type, ''PRDT0200'' product_type from dual) x where d.lang(+) = com_ui_user_env_pkg.get_user_lang and d.dict(+)||code(+) = x.entity_type', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (341, NULL, 'select id code, label name from prd_ui_service_type_vw where lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (352, NULL, 'select s.id code, s.label name, p.product_id, t.entity_type from prd_ui_product_service_vw p, prd_ui_service_vw s, prd_service_type t where s.id = p.service_id and t.id = s.service_type_id connect by prior p.id = p.parent_id and s.lang = com_ui_user_env_pkg.get_user_lang start with p.parent_id is null and s.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 1)
/
update com_lov set is_parametrized = 1, lov_query = 'select s.id code, s.label name, x.product_id from (select p.id product_id, s.id service_id from prd_product_vw p, prd_service_vw s minus select p.product_id, p.service_id from prd_product_service_vw p) x,prd_ui_service_vw s,prd_service_type_vw t,prd_product_vw p where s.status = ''SRVS0001'' and x.service_id = s.id and t.id = s.service_type_id and p.id = x.product_id and p.product_type = t.product_type and s.lang = com_ui_user_env_pkg.get_user_lang' where id = 284
/
update com_lov set lov_query = 'select distinct dict||code as code, name, lang, t.customer_entity_type, t.product_type, d.inst_id institution_id from com_ui_dictionary_vw d, prd_contract_type_vw t where d.dict = ''CNTP'' and t.contract_type = d.dict||code and d.lang = com_ui_user_env_pkg.get_user_lang' where id = 154
/
update com_lov set lov_query = 'select d.dict || d.code code, d.name, x.product_type from com_ui_dictionary_vw d,(select ''ENTTAGNT'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTINST'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTCARD'' entity_type, ''PRDT0100'' product_type from dual union all  select ''ENTTCNTR'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTCUST'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTMRCH'' entity_type, ''PRDT0200'' product_type from dual union all select ''ENTTTRMN'' entity_type, ''PRDT0200'' product_type from dual) x where d.lang(+) = com_ui_user_env_pkg.get_user_lang and d.dict(+)||code(+) = x.entity_type' where id = 319
/
-- Extend name/label columns in LOVs with service_number/product_number field as a prefix
update com_lov set lov_query = 'select id as code, case when service_number is not null then service_number || '' - '' else null end || label as name, inst_id as institution_id from prd_ui_service_vw' where id = 182
/
update com_lov set lov_query = 'select p.id as code, case when s.service_number is not null then s.service_number || '' - '' else null end || s.label as name, p.product_id from prd_ui_service_vw s, prd_ui_product_service_vw p where s.id = p.service_id connect by prior p.id = p.parent_id and s.lang = com_ui_user_env_pkg.get_user_lang start with p.parent_id is null and s.lang = com_ui_user_env_pkg.get_user_lang' where id = 283
/
update com_lov set lov_query = 'select s.id as code, case when s.service_number is not null then s.service_number || '' - '' else null end || s.label as name, x.product_id from (select p.id product_id, s.id service_id from prd_product_vw p, prd_service_vw s minus select p.product_id, p.service_id from prd_product_service_vw p) x,prd_ui_service_vw s,prd_service_type_vw t,prd_product_vw p where s.status = ''SRVS0001'' and x.service_id = s.id and t.id = s.service_type_id and p.id = x.product_id and p.product_type = t.product_type and s.lang = com_ui_user_env_pkg.get_user_lang' where id = 284
/
update com_lov set lov_query = 'select s.id as code, case when s.service_number is not null then s.service_number || '' - '' else null end || s.label as name, p.product_id, t.entity_type from prd_ui_service_vw s, prd_ui_product_service_vw p, prd_service_type t where s.id = p.service_id and t.id = s.service_type_id connect by prior p.id = p.parent_id and s.lang = com_ui_user_env_pkg.get_user_lang start with p.parent_id is null and s.lang = com_ui_user_env_pkg.get_user_lang' where id = 352
/
update com_lov set lov_query = 'select s.id as code, case when nvl(s.service_number, s.id) != to_char(s.id) then s.service_number || '' - '' else null end || s.label as name, x.product_id from (select p.id product_id, s.id service_id from prd_product_vw p, prd_service_vw s minus select p.product_id, p.service_id from prd_product_service_vw p) x, prd_ui_service_vw s, prd_service_type_vw t, prd_product_vw p where x.service_id = s.id and t.id = s.service_type_id and p.id = x.product_id and p.product_type = t.product_type and s.status = ''SRVS0001'' and s.lang = com_ui_user_env_pkg.get_user_lang()' where id = 284
/
update com_lov set lov_query = 'select s.id as code, case when s.service_number is not null then s.service_number || '' - '' else null end || s.label as name, p.product_id, t.entity_type, t.is_initial from prd_ui_service_vw s, prd_ui_product_service_vw p, prd_service_type t where s.id = p.service_id and t.id = s.service_type_id connect by prior p.id = p.parent_id and s.lang = com_ui_user_env_pkg.get_user_lang start with p.parent_id is null and s.lang = com_ui_user_env_pkg.get_user_lang' where id = 352
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (442, 'PRDS', NULL, 'PRD', 'LVSMCODE', 'LVAPNAME', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (443, NULL, 'select id as code, decode(lvl, 1, '''', lpad(''-- '', (lvl - 1) * 3, ''-- '')) || num || '' - '' || nvl(user_name, eng_name) as name from (select id, get_text(i_table_name => ''prd_product'', i_column_name => ''label'', i_object_id => id, i_lang => get_user_lang) as user_name, get_text(i_table_name => ''prd_product'', i_column_name => ''label'', i_object_id => id, i_lang => ''LANGENG'') as eng_name, product_number as num, level as lvl from prd_product start with parent_id is null connect by prior id = parent_id)', 'PRD', 'LVSMNAME', 'LVAPNAME', 'DTTPNMBR', 0)
/
update com_lov set lov_query = 'select d.dict || d.code code, d.name, x.product_type from com_ui_dictionary_vw d, (select ''ENTTAGNT'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTINST'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTCARD'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTCUST'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTMRCH'' entity_type, ''PRDT0200'' product_type from dual union all select ''ENTTTRMN'' entity_type, ''PRDT0200'' product_type from dual) x where d.lang(+) = com_ui_user_env_pkg.get_user_lang and d.dict(+) || code(+) = x.entity_type' where id = 319
/
update com_lov set lov_query = 'select s.id as code, case when nvl(s.service_number, s.id) != to_char(s.id) then s.service_number || '' - '' else null end || s.label as name, p.product_id, t.entity_type, t.is_initial from prd_ui_service_vw s, prd_ui_product_service_vw p, prd_service_type t where s.id = p.service_id and t.id = s.service_type_id connect by prior p.id = p.parent_id and s.lang = com_ui_user_env_pkg.get_user_lang start with p.parent_id is null and s.lang = com_ui_user_env_pkg.get_user_lang' where id = 352
/
update com_lov set lov_query = 'select a.id code, a.label name, b.entity_type, s.id service from prd_ui_attribute_vw a, prd_ui_service_type_vw b, prd_ui_service_vw s where a.definition_level in (''SADLOBJT'', ''SADLPRDT'') and (a.entity_type != ''ENTTAGRP'' or a.entity_type is null) and a.lang = com_ui_user_env_pkg.get_user_lang and a.lang = b.lang and a.service_type_id = b.id and b.lang = s.lang and s.service_type_id = b.id' where id = 133
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (491, NULL, 'select distinct account_type code, com_api_dictionary_pkg.get_article_text(account_type) as name, t.inst_id from acc_account_type t where product_type = ''PRDT0300''', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 1)
/
update com_lov set lov_query = 'select s.id as code, case when nvl(s.service_number, s.id) != to_char(s.id) then s.service_number || '' - '' else null end || s.label as name, x.product_id, s.inst_id from (select p.id product_id, s.id service_id from prd_product_vw p, prd_service_vw s minus select p.product_id, p.service_id from prd_product_service_vw p) x, prd_ui_service_vw s, prd_service_type_vw t, prd_product_vw p where x.service_id = s.id and t.id = s.service_type_id and p.id = x.product_id and p.product_type = t.product_type and s.status = ''SRVS0001'' and s.lang = com_ui_user_env_pkg.get_user_lang()' where id = 284
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (1049, NULL, 'select a.object_type as code, a.label as name from prd_ui_attribute_vw a where a.entity_type in (''ENTTCYCL'', ''ENTTFEES'', ''ENTTLIMT'') and a.lang = com_ui_user_env_pkg.get_user_lang()', 'PRD', 'LVSMCODE', 'LVAPNMCD', 'DTTPCHAR', 0)
/
delete from com_lov where id = 318
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (318, NULL, 'select distinct dict||code as code, name, t.product_type from com_ui_dictionary_vw d, prd_contract_type_vw t where d.dict = ''CNTP'' and t.contract_type = d.dict||code and d.lang = com_ui_user_env_pkg.get_user_lang', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 1)
/
update com_lov set lov_query = 'select id as code, case when service_number is not null then service_number || '' - '' else null end || label as name, inst_id as institution_id from prd_ui_service_vw where lang = com_ui_user_env_pkg.get_user_lang' where id = 182
/
update com_lov set lov_query = 'select d.dict || d.code code, d.name, x.product_type from com_ui_dictionary_vw d, (select ''ENTTAGNT'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTINST'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTCARD'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTACCT'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTCUST'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTMRCH'' entity_type, ''PRDT0200'' product_type from dual union all select ''ENTTTRMN'' entity_type, ''PRDT0200'' product_type from dual) x where d.lang(+) = com_ui_user_env_pkg.get_user_lang and d.dict(+) || code(+) = x.entity_type' where id = 319
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (596, 'CNDS', NULL, 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (617, NULL, 'select num as code, decode(lvl, 1, '''', lpad(''-- '', (lvl - 1) * 3, ''-- '')) || num || '' - '' || nvl(user_name, eng_name) as name from (select id, get_text(i_table_name => ''prd_product'', i_column_name => ''label'', i_object_id => id, i_lang => get_user_lang) as user_name, get_text(i_table_name => ''prd_product'', i_column_name => ''label'', i_object_id => id, i_lang => ''LANGENG'') as eng_name, product_number as num, level as lvl from prd_product start with parent_id is null connect by prior id = parent_id)', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
update com_lov set lov_query = 'select d.dict || d.code code, d.name, x.product_type from com_ui_dictionary_vw d, (select ''ENTTAGNT'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTINST'' entity_type, ''PRDT0300'' product_type from dual union all select ''ENTTCARD'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTACCT'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTCUST'' entity_type, ''PRDT0100'' product_type from dual union all select ''ENTTMRCH'' entity_type, ''PRDT0200'' product_type from dual union all select ''ENTTTRMN'' entity_type, ''PRDT0200'' product_type from dual union all select ''ENTTCARD'' entity_type, ''PRDT0200'' product_type from dual) x where d.lang(+) = com_ui_user_env_pkg.get_user_lang and d.dict(+) || code(+) = x.entity_type' where id = 319
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized, is_depended) values (693, 'RLRA', 'select dict || code as code, name from com_ui_dictionary_vw where dict = ''RLRA'' and lang = com_ui_user_env_pkg.get_user_lang()', 'PRD', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0, NULL)
/

