package ru.bpc.sv2.accounts;

public class AccountPrivConstants {
	public static final String VIEW_ACCOUNT_TYPE = "VIEW_ACCOUNT_TYPE";
	public static final String ADD_ACCOUNT_TYPE = "ADD_ACCOUNT_TYPE";
	public static final String MODIFY_ACCOUNT_TYPE = "MODIFY_ACCOUNT_TYPE";
	public static final String REMOVE_ACCOUNT_TYPE = "REMOVE_ACCOUNT_TYPE";
	
	public static final String VIEW_ACCOUNT_BALANCE_TYPE = "VIEW_ACCOUNT_BALANCE_TYPE";
	public static final String ADD_ACCOUNT_BALANCE_TYPE = "ADD_ACCOUNT_BALANCE_TYPE";
	public static final String MODIFY_ACCOUNT_BALANCE_TYPE = "MODIFY_ACCOUNT_BALANCE_TYPE";
	public static final String REMOVE_ACCOUNT_BALANCE_TYPE = "REMOVE_ACCOUNT_BALANCE_TYPE";
	
	public static final String VIEW_ACCOUNT_ENTRY_TEMPLATE = "VIEW_ACCOUNT_ENTRY_TEMPLATE";
	public static final String ADD_ACCOUNT_ENTRY_TEMPLATE = "ADD_ACCOUNT_ENTRY_TEMPLATE";
	public static final String MODIFY_ACCOUNT_ENTRY_TEMPLATE = "MODIFY_ACCOUNT_ENTRY_TEMPLATE";
	public static final String REMOVE_ACCOUNT_ENTRY_TEMPLATE = "REMOVE_ACCOUNT_ENTRY_TEMPLATE";
	
	public static final String VIEW_ACCOUNT_MACROS_TYPE = "VIEW_ACCOUNT_MACROS_TYPE";
	public static final String ADD_ACCOUNT_MACROS_TYPE = "ADD_ACCOUNT_MACROS_TYPE";
	public static final String MODIFY_ACCOUNT_MACROS_TYPE = "MODIFY_ACCOUNT_MACROS_TYPE";
	public static final String REMOVE_ACCOUNT_MACROS_TYPE = "REMOVE_ACCOUNT_MACROS_TYPE";
	
	public static final String VIEW_ACCOUNT = "VIEW_ACCOUNT";
	public static final String VIEW_ISSUING_ACCOUNTS = "VIEW_ISSUING_ACCOUNTS";
	public static final String VIEW_ACQUIRING_ACCOUNTS = "VIEW_ACQUIRING_ACCOUNTS";
	public static final String VIEW_TAB_ACCOUNT = "VIEW_TAB_ACCOUNT";
	
	public static final String VIEW_ACCOUNT_TYPE_ENTITY = "VIEW_ACCOUNT_TYPE_ENTITY";
	public static final String ADD_ACCOUNT_TYPE_ENTITY = "ADD_ACCOUNT_TYPE_ENTITY";
	public static final String MODIFY_ACCOUNT_TYPE_ENTITY = "MODIFY_ACCOUNT_TYPE_ENTITY";
	public static final String REMOVE_ACCOUNT_TYPE_ENTITY = "REMOVE_ACCOUNT_TYPE_ENTITY";
	
	public static final String VIEW_ACCOUNT_BALANCES = "VIEW_ACCOUNT_BALANCES";
	public static final String VIEW_TRANSACTION = "VIEW_TRANSACTION";
	
	public static final String VIEW_ACCOUNT_ENTRY_SET = "VIEW_ACCOUNT_ENTRY_SET";
	public static final String ADD_ACCOUNT_ENTRY_SET = "ADD_ACCOUNT_ENTRY_SET";
	public static final String MODIFY_ACCOUNT_ENTRY_SET = "MODIFY_ACCOUNT_ENTRY_SET";
	public static final String REMOVE_ACCOUNT_ENTRY_SET = "REMOVE_ACCOUNT_ENTRY_SET";
	
	public static final String VIEW_ACCOUNT_SELECTION_ALGORITHM = "VIEW_ACCOUNT_SELECTION_ALGORITHM";
	public static final String ADD_ACCOUNT_SELECTION_ALGORITHM = "ADD_ACCOUNT_SELECTION_ALGORITHM";
	public static final String MODIFY_ACCOUNT_SELECTION_ALGORITHM = "MODIFY_ACCOUNT_SELECTION_ALGORITHM";
	public static final String REMOVE_ACCOUNT_SELECTION_ALGORITHM = "REMOVE_ACCOUNT_SELECTION_ALGORITHM";
	
	public static final String VIEW_ACCOUNT_SELECTION_STEPS = "VIEW_ACCOUNT_SELECTION_STEPS";
	public static final String ADD_ACCOUNT_SELECTION_STEP = "ADD_ACCOUNT_SELECTION_STEP";
	public static final String MODIFY_ACCOUNT_SELECTION_STEP = "MODIFY_ACCOUNT_SELECTION_STEP";
	public static final String REMOVE_ACCOUNT_SELECTION_STEP = "REMOVE_ACCOUNT_SELECTION_STEP";
	
	public static final String VIEW_ACCOUNT_SELECTION_PRIORITY = "VIEW_ACCOUNT_SELECTION_PRIORITY";
	public static final String ADD_ACCOUNT_SELECTION_PRIORITY = "ADD_ACCOUNT_SELECTION_PRIORITY";
	public static final String MODIFY_ACCOUNT_SELECTION_PRIORITY = "MODIFY_ACCOUNT_SELECTION_PRIORITY";
	public static final String REMOVE_ACCOUNT_SELECTION_PRIORITY = "REMOVE_ACCOUNT_SELECTION_PRIORITY";
	public static final String VIEW_TAB_ACCOUNT_SELECTION_PRIORITY = "VIEW_TAB_ACCOUNT_SELECTION_PRIORITY";
	
	public static final String VIEW_GL_ACCOUNT = "VIEW_GL_ACCOUNT";
	public static final String VIEW_TAB_GL_ACCOUNT = "VIEW_TAB_GL_ACCOUNT";
	
	public static final String VIEW_ISO_ACCOUNT_TYPE = "VIEW_ISO_ACCOUNT_TYPE";
	public static final String ADD_ISO_ACCOUNT_TYPE = "ADD_ISO_ACCOUNT_TYPE";
	public static final String MODIFY_ISO_ACCOUNT_TYPE = "MODIFY_ISO_ACCOUNT_TYPE";
	public static final String REMOVE_ISO_ACCOUNT_TYPE = "REMOVE_ISO_ACCOUNT_TYPE";
	
	public static final String VIEW_ENTRY_TEMPLATE_PAIR = "VIEW_ENTRY_TEMPLATE_PAIR";
	public static final String ADD_ENTRY_TEMPLATE_PAIR = "ADD_ENTRY_TEMPLATE_PAIR";
	public static final String MODIFY_ENTRY_TEMPLATE_PAIR = "MODIFY_ENTRY_TEMPLATE_PAIR";
	public static final String REMOVE_ENTRY_TEMPLATE_PAIR = "REMOVE_ENTRY_TEMPLATE_PAIR";

	public static final String VIEW_PRODUCT_ACCOUNT_TYPE = "VIEW_PRODUCT_ACCOUNT_TYPE";
	public static final String ADD_PRODUCT_ACCOUNT_TYPE = "ADD_PRODUCT_ACCOUNT_TYPE";
	public static final String MODIFY_PRODUCT_ACCOUNT_TYPE = "MODIFY_PRODUCT_ACCOUNT_TYPE";
	public static final String REMOVE_PRODUCT_ACCOUNT_TYPE = "REMOVE_PRODUCT_ACCOUNT_TYPE";
	
	public static final String VIEW_BUNCH_TYPES = "VIEW_BUNCH_TYPES";

	public static final String VIEW_PRIORITY_ACCOUNTS = "VIEW_PRIORITY_ACCOUNTS";
}
