create or replace force view cup_fin_message_vw as
select id
     , status
     , is_reversal
     , is_incoming
     , is_rejected
     , is_invalid
     , inst_id
     , network_id
     , host_inst_id
     , collect_only_flag
     , rrn
     , merchant_number
     , acquirer_iin
     , trans_amount
     , app_version_no
     , appl_charact
     , appl_crypt
     , auth_amount
     , auth_method
     , auth_resp_code
     , terminal_capab
     , card_serial_num
     , cipher_text_inf_data
     , auth_currency
     , terminal_country
     , dedic_doc_name
     , ic_card_cond_code
     , interface_serial
     , iss_bank_app_data
     , local
     , mcc
     , merchant_name
     , other_amount
     , point
     , proc_func_code
     , terminal_entry_capab
     , terminal_verif_result
     , script_result_of_card_issuer
     , forwarding_iin
     , pos_entry_mode
     , sys_trace_num
     , terminal_category
     , terminal_number
     , trans_currency
     , trans_init_channel
     , trans_category
     , trans_counter
     , trans_date
     , trans_resp_code
     , trans_serial_counter
     , trans_code
     , transmission_date_time
     , unpred_num
     , file_id
     , msg_number
     , cardholder_exch_rate
     , cardholder_acc_currency
     , cardholder_bill_amount
     , cups_notice
     , cups_ref_num
     , double_message_id
     , int_org
     , issue
     , issuer_iin
     , payment_service_type
     , pos_input_mode
     , reason_code
     , receiving_iin
     , service_fee_amount
     , service_fee_currency
     , service_fee_exch_rate
     , settlement_exch_rate
     , terminal_auth_date
     , trans_features_id
     , transferred
     , ic_trans_currency_code
     , ic_pos_input_mode
     , original_id
     , merchant_country
     , pos_cond_code
     , orig_trans_code
     , orig_sys_trace_num
     , orig_trans_date
     , orig_transmission_date_time
     , sttl_amount
     , sttl_currency
     , message_type
     , receivable_fee
     , payable_fee
     , dispute_id
     , b2b_business_type
     , b2b_payment_medium
     , qrc_voucher_number
     , payment_facilitator_id
  from cup_fin_message
/
