insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (1027, 'DPPA', NULL, 'DPP', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (196, 'DPAT', NULL, 'DPP', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (198, NULL, 'select d.percent_rate as code ,get_article_text(e.fee_type ,get_user_lang) as name from prd_attribute_vw a ,prd_attribute_value_vw b ,fcl_fee_tier_vw d ,fcl_fee_vw e where a.attr_name = ''DPP_INTEREST_RATE'' and a.id = b.attr_id and b.attr_value = d.fee_id and d.sum_threshold = 0 and d.count_threshold = 0 and e.id = d.fee_id and b.end_date>get_sysdate', 'DPP', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (199, NULL, 'select to_number(b.attr_value, ''FM000000000000000000.0000'') code, fcl_ui_fee_pkg.get_fee_desc(to_number(b.attr_value, ''FM000000000000000000.0000'')) name, a.id account_id from acc_account a, prd_ui_product_attr_value_vw b where b.product_id = prd_api_product_pkg.get_product_id(''ENTTACCT'', a.id) and b.attr_name = ''DPP_INTEREST_RATE'' and b.lang = com_ui_user_env_pkg.get_user_lang and get_sysdate between start_date and nvl(end_date, get_sysdate)', 'DPP', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
update com_lov set is_parametrized = 1 where id in (199)
/
update com_lov set lov_query = 'select to_number(b.attr_value, ''FM000000000000000000.0000'') code, fcl_ui_fee_pkg.get_fee_desc(to_number(b.attr_value, ''FM000000000000000000.0000'')) name, a.id account_id from acc_account a, prd_ui_product_attr_value_vw b where b.product_id = prd_api_product_pkg.get_product_id(i_entity_type => ''ENTTACCT'', i_object_id => a.id) and b.attr_name = ''DPP_INTEREST_RATE'' and b.lang = com_ui_user_env_pkg.get_user_lang and get_sysdate between start_date and nvl(end_date, get_sysdate)' where id = 199
/
update com_lov set lov_query = 'select to_number(b.attr_value, ''FM000000000000000000.0000'') code, fcl_ui_fee_pkg.get_fee_desc(to_number(b.attr_value, ''FM000000000000000000.0000'')) name, a.id account_id from acc_account a, (select product_id, attr_name, attr_value, lang, start_date, end_date from (select dense_rank() over(partition by product_id, service_id, attr_id, lang order by start_date desc) rn, product_id, attr_name, attr_value, lang, start_date, end_date from prd_ui_product_attr_value_vw where start_date <= get_sysdate) where rn = 1) b where b.product_id = prd_api_product_pkg.get_product_id(i_entity_type => ''ENTTACCT'', i_object_id => a.id) and b.attr_name = ''DPP_INTEREST_RATE'' and b.lang = com_ui_user_env_pkg.get_user_lang and get_sysdate between start_date and nvl(end_date, get_sysdate)' where id = 199
/
update com_lov set lov_query = 'select to_number(b.attr_value, ''FM000000000000000000.0000'') code, fcl_ui_fee_pkg.get_fee_desc(to_number(b.attr_value, ''FM000000000000000000.0000'')) name, a.id account_id from acc_account a, (select product_id, attr_name, attr_value, lang, start_date, end_date from (select dense_rank() over (partition by product_id, service_id, attr_id, lang order by start_date desc) rn, product_id, attr_name, attr_value, lang, start_date, end_date from prd_ui_product_attr_value_vw where attr_name = ''DPP_INTEREST_RATE'' and get_sysdate between start_date and nvl(end_date, get_sysdate)) where rn = 1) b where b.product_id = prd_api_product_pkg.get_product_id(i_entity_type => ''ENTTACCT'', i_object_id => a.id) and b.lang = com_ui_user_env_pkg.get_user_lang' where id = 199
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (608, 'DPPR', NULL, 'DPP', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
update com_lov set appearance = 'LVAPNAME', sort_mode = 'LVSMNAMD', lov_query = 'select to_number(b.attr_value, ''FM000000000000000000.0000'') as code, fcl_ui_fee_pkg.get_fee_desc(to_number (b.attr_value, ''FM000000000000000000.0000'')) || case when b.mod_id is not null then '' - '' || get_text(''rul_mod'', ''name'', b.mod_id) end as name, a.id as account_id from acc_account a, (select v.product_id, v.attr_name, v.attr_value, v.mod_id, v.lang, v.start_date, v.end_date from (select dense_rank () over (partition by t.product_id, t.service_id, t.attr_id, t.mod_id, t.lang order by t.start_date desc) rn, t.* from prd_ui_product_attr_value_vw t where t.attr_name = ''DPP_INTEREST_RATE'' and get_sysdate between t.start_date and nvl(t.end_date, get_sysdate)) v where v.rn = 1) b where b.product_id = prd_api_product_pkg.get_product_id(i_entity_type => ''ENTTACCT'', i_object_id => a.id) and b.lang = com_ui_user_env_pkg.get_user_lang()' where id = 199
/
update com_lov set lov_query = 'select to_number(b.attr_value, ''FM000000000000000000.0000'') as code, fcl_ui_fee_pkg.get_fee_desc(to_number (b.attr_value, ''FM000000000000000000.0000'')) || case when b.mod_id is not null then '' - '' || get_text(''rul_mod'', ''name'', b.mod_id) end as name, a.id as account_id from acc_account a, (select v.product_id, v.attr_name, v.attr_value, v.mod_id, v.lang, v.start_date, v.end_date from (select dense_rank () over (partition by t.product_id, t.service_id, t.attr_id, t.mod_id, t.lang order by t.start_date desc) rn, t.* from prd_ui_product_attr_value_vw t where t.attr_name = ''DPP_INTEREST_RATE'' and t.mod_id is null and get_sysdate between t.start_date and nvl(t.end_date, get_sysdate)) v where v.rn = 1) b where b.product_id = prd_api_product_pkg.get_product_id(i_entity_type => ''ENTTACCT'', i_object_id => a.id) and b.lang = com_ui_user_env_pkg.get_user_lang()' where id = 199
/
