insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000005, 1319, -50000007, NULL, NULL, -5085, 1, NULL, NULL, NULL, 0, 0, 9999, -50000022, -50000020, NULL, 'FSIT0000', NULL, 0, 1000, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000004, 1319, -50000006, NULL, NULL, -5084, 1, NULL, NULL, NULL, 0, 0, 9999, -50000021, -50000019, NULL, 'FSIT0000', NULL, 0, 1000, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000003, 1319, -50000005, NULL, NULL, -5084, 1, NULL, NULL, NULL, 0, 0, 9999, -50000021, -50000019, NULL, 'FSIT0000', NULL, 0, 1000, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000002, 1319, -50000004, NULL, NULL, -5084, 1, NULL, NULL, NULL, 0, 0, 9999, -50000021, -50000019, NULL, 'FSIT0000', NULL, 0, 1000, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000001, 1319, -50000003, NULL, NULL, -5084, 1, NULL, NULL, NULL, 0, 0, 9999, -50000021, -50000019, NULL, 'FSIT0000', NULL, 0, 1000, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000006, -5152, -50000011, 'UTF-8', '.*sms.*', NULL, 0, NULL, NULL, NULL, 0, 0, 9999, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000007, -5160, -50000013, 'UTF-8', NULL, -5094, 0, NULL, NULL, NULL, 0, 0, 9999, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
insert into prc_file_attribute (id, file_id, container_id, characterset, file_name_mask, name_format_id, upload_empty_file, location, xslt_source, converter_class, is_tar, is_zip, inst_id, report_id, report_template_id, load_priority, sign_transfer_type, encrypt_plugin, ignore_file_errors, location_id, parallel_degree, is_file_name_unique, is_file_required, is_cleanup_data, queue_identifier, time_out, port, line_separator, password_protect) values (-50000008, -5161, -50000014, 'UTF-8', NULL, -5094, 0, NULL, NULL, NULL, 0, 0, 9999, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, NULL, NULL, NULL, 'OS-defined', 0)
/
