pipeline {
    parameters {
        string(name: 'RESOURCE_FILE', defaultValue: 'core_sv_clear', description: 'Set  parameter of resource file')
    }
    agent { label 'linux' }
    stages {
        stage('Get SV_Installer') {
            steps {
                ansiColor('xterm') {
                    script {
                        // currentBuild.displayName = "The name."
                        // currentBuild.description = "cleanup on ${params.HOST}"
                        sh "curl -s http://sv2.bpc.in/share/installer/get_installer.sh | bash"
                        sh "ls -la"
                    }
                }
            }
        }
        stage('Config SV_Installer') {
            steps {
                ansiColor('xterm') {
                    script {
                        // currentBuild.displayName = "The name."
                        // currentBuild.description = "cleanup on ${params.HOST}"
                        echo "Test pipeline"
                    }
                }
            }
        }
        stage('Extract via SV_Installer') {
            steps {
                ansiColor('xterm') {
                    script {
                        // currentBuild.displayName = "The name."
                        // currentBuild.description = "cleanup on ${params.HOST}"
                        echo "Test pipeline"
                    }
                }
            }
        }
        stage('Deploy via SV_Installer') {
            steps {
                ansiColor('xterm') {
                    script {
                        // currentBuild.displayName = "The name."
                        // currentBuild.description = "cleanup on ${params.HOST}"
                        echo "Test pipeline"
                    }
                }
            }
        }
    }
}
