create global temporary table cst_smt_international_cl_tmp
(
  oper_id                    number(16)         not null,
  iss_event_id               number(16),
  acq_event_id               number(16),
  oper_code                  varchar2(2),
  merchant_number            varchar2(10),
  processing_date            date,
  merchant_rib               varchar2(24),
  merchant_name              varchar2(25),
  merchant_address           varchar2(25),
  territory_code             number(1),
  merchant_type              varchar2(1),
  branch_code                varchar2(5),
  batch_number               varchar2(6),
  batch_date                 date,
  oper_amount                number(22),
  card_country               varchar2(3),
  oper_currency              varchar2(3),
  sttl_amount                number(22),
  interchange_fee            number(22),
  tax_amount                 number(22),
  commission_without_tax     number(22),
  device_type                varchar2(1),
  issuer_inst_id             varchar2(4),
  acquirer_inst_id           varchar2(4),
  batch_id                   varchar2(7),
  oper_channel               varchar2(1),
  orinator_refnum            varchar2(12),
  pan                        varchar2(19),
  card_expire_date           date,
  arn                        varchar2(23),
  auth_code                  varchar2(6),
  invoice                    varchar2(6),
  sttl_currency              varchar2(3),
  tax_on_interchange         number(22),
  merchant_comission         number(22),
  tax_on_merchant_comission  number(22),
  oper_type                  varchar2(8),
  issuer_agent_id            number(8),
  mcc                        varchar2(4),
  card_type_id               number(4),
  card_network_id            number(4),
  merchant_id                number(8)
)
on commit delete rows
/
