package ru.bpc.sv2.wizard;

public interface WizardPrivConstants {
    String CARD_OPERATION_MAKER = "CARD_OPERATION_MAKER";
    String CARD_OPERATION_CHECKER  = "CARD_OPERATION_CHECKER";

    String ACCOUNT_BALANCE_CORRECTION_MAKER = "ACCOUNT_BALANCE_CORRECTION_MAKER";
    String ACCOUNT_BALANCE_CORRECTION_CHECKER = "ACCOUNT_BALANCE_CORRECTION_CHECKER";

    String CARD_CHANGE_STATUS_MAKER = "CARD_CHANGE_STATUS_MAKER";
    String CARD_CHANGE_STATUS_CHECKER = "CARD_CHANGE_STATUS_CHECKER";

    String CARD_CHANGE_LIMIT_AMOUNT_MAKER = "CARD_CHANGE_LIMIT_AMOUNT_MAKER";
    String CARD_CHANGE_LIMIT_AMOUNT_CHECKER = "CARD_CHANGE_LIMIT_AMOUNT_CHECKER";

    String CARD_MANUAL_FEE_MAKER = "CARD_MANUAL_FEE_MAKER";
    String CARD_MANUAL_FEE_CHECKER = "CARD_MANUAL_FEE_CHECKER";

    String ACCOUNT_CHANGE_LIMIT_AMOUNT_MAKER = "ACCOUNT_CHANGE_LIMIT_AMOUNT_MAKER";
    String ACCOUNT_CHANGE_LIMIT_AMOUNT_CHECKER = "ACCOUNT_CHANGE_LIMIT_AMOUNT_CHECKER";

    String ACCOUNT_MANUAL_FEE_MAKER = "ACCOUNT_MANUAL_FEE_MAKER";
    String ACCOUNT_MANUAL_FEE_CHECKER = "ACCOUNT_MANUAL_FEE_CHECKER";

    String CARD_DETACH_SERVICE_MAKER = "CARD_DETACH_SERVICE_MAKER";
    String CARD_DETACH_SERVICE_CHECKER = "CARD_DETACH_SERVICE_CHECKER";

    String CARD_UNHOLD_MAKER = "CARD_UNHOLD_MAKER";
    String CARD_UNHOLD_CHECKER = "CARD_UNHOLD_CHECKER";

    String ACCOUNT_COMMON_OPERATION_ISS_MAKER = "ACCOUNT_COMMON_OPERATION_ISS_MAKER";
    String ACCOUNT_COMMON_OPERATION_ISS_CHECKER = "ACCOUNT_COMMON_OPERATION_ISS_CHECKER";

    String ACCOUNT_COMMON_OPERATION_ACQ_MAKER = "ACCOUNT_COMMON_OPERATION_ACQ_MAKER";
    String ACCOUNT_COMMON_OPERATION_ACQ_CHECKER = "ACCOUNT_COMMON_OPERATION_ACQ_CHECKER";

    String ACCOUNT_CHANGE_STATUS_MAKER = "ACCOUNT_CHANGE_STATUS_MAKER";
    String ACCOUNT_CHANGE_STATUS_CHECKER = "ACCOUNT_CHANGE_STATUS_CHECKER";

    String ACCOUNT_CHANGE_BALANCE_MAKER = "ACCOUNT_CHANGE_BALANCE_MAKER";
    String ACCOUNT_CHANGE_BALANCE_CHECKER = "ACCOUNT_CHANGE_BALANCE_CHECKER";

    String ACCOUNT_PROVIDE_CREDIT_LIMIT_MAKER = "ACCOUNT_PROVIDE_CREDIT_LIMIT_MAKER";
    String ACCOUNT_PROVIDE_CREDIT_LIMIT_CHECKER = "ACCOUNT_PROVIDE_CREDIT_LIMIT_CHECKER";

    String OPERATION_REPROCESSING_MAKER = "OPERATION_REPROCESSING_MAKER";
    String OPERATION_REPROCESSING_CHECKER = "OPERATION_REPROCESSING_CHECKER";

    String OPERATION_MATCH_MAKER = "OPERATION_MATCH_MAKER";
    String OPERATION_MATCH_CHECKER = "OPERATION_MATCH_CHECKER";

    String OPERATION_CHANGE_STATUS_MAKER = "OPERATION_CHANGE_STATUS_MAKER";
    String OPERATION_CHANGE_STATUS_CHECKER = "OPERATION_CHANGE_STATUS_CHECKER";

    String OPERATION_MATCH_REVERSAL_MAKER = "OPERATION_MATCH_REVERSAL_MAKER";
    String OPERATION_MATCH_REVERSAL_CHECKER = "OPERATION_MATCH_REVERSAL_CHECKER";

    String COMMON_OPERATION_MAKER = "COMMON_OPERATION_MAKER";
    String COMMON_OPERATION_CHECKER = "COMMON_OPERATION_CHECKER";

    String ACCOUNT_FUNDS_TRANSFER_MAKER = "ACCOUNT_FUNDS_TRANSFER_MAKER";
    String ACCOUNT_FUNDS_TRANSFER_CHECKER = "ACCOUNT_FUNDS_TRANSFER_CHECKER";

    String ACCOUNT_FUNDS_TRANSFER_BETWEEN_MAKER = "ACCOUNT_FUNDS_TRANSFER_BETWEEN_MAKER";
    String ACCOUNT_FUNDS_TRANSFER_BETWEEN_CHECKER = "ACCOUNT_FUNDS_TRANSFER_BETWEEN_CHECKER";

    String COMMON_CHANGE_FRAUD_STATUS_MAKER = "COMMON_CHANGE_FRAUD_STATUS_MAKER";
    String COMMON_CHANGE_FRAUD_STATUS_CHECKER = "COMMON_CHANGE_FRAUD_STATUS_CHECKER";

    String CARD_REWARD_LOYALTY_MAKER = "CARD_REWARD_LOYALTY_MAKER";
    String CARD_REWARD_LOYALTY_CHECKER = "CARD_REWARD_LOYALTY_CHECKER";

    String CARD_SERVICE_NOTIFICATION_MAKER = "CARD_SERVICE_NOTIFICATION_MAKER";
    String CARD_SERVICE_NOTIFICATION_CHECKER = "CARD_SERVICE_NOTIFICATION_CHECKER";

    String COMMON_BALANCE_TRANSFER_FROM_PREPAID_CARD_MAKER = "COMMON_BALANCE_TRANSFER_FROM_PREPAID_CARD_MAKER";
    String COMMON_BALANCE_TRANSFER_FROM_PREPAID_CARD_CHECKER = "COMMON_BALANCE_TRANSFER_FROM_PREPAID_CARD_CHECKER";

    String FEE_COLLECTION_MAKER = "FEE_COLLECTION_MAKER";
    String FEE_COLLECTION_CHECKER = "FEE_COLLECTION_CHECKER";

    String OPERATION_CREDIT_BALANCE_TRANSFER_MAKER = "OPERATION_CREDIT_BALANCE_TRANSFER_MAKER";
    String OPERATION_CREDIT_BALANCE_TRANSFER_CHECKER = "OPERATION_CREDIT_BALANCE_TRANSFER_CHECKER";

    String OPERATION_ROLLBACK_CREDIT_BALANCE_TRANSFER_MAKER = "OPERATION_ROLLBACK_CREDIT_BALANCE_TRANSFER_MAKER";
    String OPERATION_ROLLBACK_CREDIT_BALANCE_TRANSFER_CHECKER = "OPERATION_ROLLBACK_CREDIT_BALANCE_TRANSFER_CHECKER";

    String ADD_INSTALMENT_PLAN_CHECKER = "ADD_INSTALMENT_PLAN_CHECKER";
    String ADD_INSTALMENT_PLAN_MAKER = "ADD_INSTALMENT_PLAN_MAKER";

	String MESSAGE_OPER_FOR_NOT_RCN_MSG_MAKER   = "MESSAGE_OPER_FOR_NOT_RCN_MSG_MAKER";
	String MESSAGE_OPER_FOR_NOT_RCN_MSG_CHECKER = "MESSAGE_OPER_FOR_NOT_RCN_MSG_CHECKER";

    String REMOVE_INSTALMENT_PLAN_MAKER = "REMOVE_INSTALMENT_PLAN_MAKER";
    String REMOVE_INSTALMENT_PLAN_CHECKER = "REMOVE_INSTALMENT_PLAN_CHECKER";

    String CARD_REISSUE_REQUEST   = "CARD_REISSUE_REQUEST";
    String CARD_REISSUE = "CARD_REISSUE";

    String CHANGE_CARD_PRODUCT_REQUEST   = "CHANGE_CARD_PRODUCT_REQUEST";
    String CHANGE_CARD_PRODUCT = "CHANGE_CARD_PRODUCT";

	String MODIFY_INSTALMENT_PLAN_MAKER = "MODIFY_INSTALMENT_PLAN_MAKER";
	String MODIFY_INSTALMENT_PLAN_CHECKER = "MODIFY_INSTALMENT_PLAN_CHECKER";
}
