package ru.bpc.sv2.operations.constants;

public interface OperationsConstants {
	String OPERATION_STATUS_PROCESS_READY			= "OPST0100";

	String SETTLEMENT_INTERNAL_INTRAINST			= "STTT0000";

	String MESSAGE_TYPE_PRESENTMENT					= "MSGTPRES";
	String MESSAGE_TYPE_AUTHORIZATION				= "MSGTAUTH";
	String MESSAGE_TYPE_PREAUTHORIZATION			= "MSGTPREU";
	String MESSAGE_TYPE_COMPLETION					= "MSGTCMPL";

	String MATCH_STATUS_MATCHED						= "MTST0500";
	String MATCH_STATUS_REQUIRE_MATCHING			= "MTST0200";

	String FEE_COLLECTION_CREDIT_TO_ORIGINATOR	    = "OPTP0019";
	String FEE_COLLECTION_DEBIT_TO_ORIGINATOR       = "OPTP0029";

	String OPERATION_TYPE_INTERNAL_TRANSFER			= "OPTP0041";

	String IDENT_TYPE_UNDEFINED						= "CITPUNKN";
	String IDENT_TYPE_NONE							= "CITPNONE";
	String IDENT_TYPE_CARD							= "CITPCARD";
	String IDENT_TYPE_ACCOUNT						= "CITPACCT";
	String IDENT_TYPE_MOBILE						= "CITPMBPH";
	String IDENT_TYPE_EMAIL							= "CITPEMAI";
	String IDENT_TYPE_CUSTOMER						= "CITPCUST";
	String IDENT_TYPE_CONTRACT						= "CITPCNTR";
}
