create table ntf_message (
    id                  number(16)
    , part_key          as (to_date(substr(lpad(to_char(id), 16, '0'), 1, 6), 'yymmdd')) virtual -- [@skip patch]
    , channel_id        number(4)
    , text              clob
    , lang              varchar2(8)
    , delivery_address  varchar2(200)
    , delivery_date     date
    , is_delivered      number(1)
    , urgency_level     number(4)
)
/****************** partition start ********************
partition by range (part_key) interval(numtoyminterval(1, 'MONTH'))                 -- [@skip patch]
(                                                                                   -- [@skip patch]
    partition ntf_message_p01 values less than (to_date('1-1-2017','DD-MM-YYYY'))   -- [@skip patch]
)                                                                                   -- [@skip patch]
******************** partition end ********************/
/
comment on table ntf_message is 'Messages prepared for delivery.'
/
comment on column ntf_message.id is 'Primary key.'
/
comment on column ntf_message.channel_id is 'Reference to delivery channel.'
/
comment on column ntf_message.text is 'Message content.'
/
comment on column ntf_message.lang is 'Message language'
/
comment on column ntf_message.delivery_address is 'Delivery address.'
/
comment on column ntf_message.delivery_date is 'Delivery date. Message can be delivered after that date.'
/
comment on column ntf_message.is_delivered is 'Flag if message was delivered.'
/
comment on column ntf_message.urgency_level is 'Message urgency level (0 - high urgency, 1- normal urgency, 2 - low urgency etc)'
/

alter table ntf_message add (inst_id number(4))
/
comment on column ntf_message.inst_id is 'Institution identifier.'
/

alter table ntf_message add (event_type  varchar2(8))
/
comment on column ntf_message.event_type is 'Event type code.'
/
alter table ntf_message add (eff_date  date)
/
comment on column ntf_message.eff_date is 'Event effective date.'
/
alter table ntf_message add (entity_type  varchar2(8))
/
comment on column ntf_message.entity_type is 'Business-entity type.'
/
alter table ntf_message add (object_id  number(16))
/
comment on column ntf_message.object_id is 'Reference to the object.'
/
alter table ntf_message add (sms_gate_reference  number(8))
/
comment on column ntf_message.sms_gate_reference is 'Message identifier for updating status from sms-gate.'
/
alter table ntf_message add (message_status  varchar2(8))
/
comment on column ntf_message.message_status is 'Status of message from sms-gate (dictionary SGMS).'
/
alter table ntf_message add (gate_ref_no  varchar2(70))
/
comment on column ntf_message.gate_ref_no is 'Message identifier from sms-gate.'
/
alter table ntf_message add (delivery_time  varchar2(200))
/
comment on column ntf_message.delivery_time is 'Time interval for delivery. filled in format xx-yy. where xx start hour and yy end hour.'
/

alter table ntf_message rename column gate_ref_no to message_status_reference
/
comment on column ntf_message.sms_gate_reference is 'Primary message identifier generated by system for SMS gate.'
/
comment on column ntf_message.message_status_reference is 'SMS gate message identifier used for update message status if message was not delivered immediately. Generated by SMS-gate.'
/
alter table ntf_message modify delivery_address varchar2(2000)
/
begin
    for rec in (select count(1) cnt from user_tab_columns where table_name = 'NTF_MESSAGE' and column_name = 'PART_KEY')
    loop
        if rec.cnt = 0 then
            execute immediate 'alter table ntf_message add (part_key as (to_date(substr(lpad(to_char(id), 16, ''0''), 1, 6), ''yymmdd'')) virtual)';
            execute immediate 'comment on column ntf_message.part_key is ''Partition key''';
        end if;
    end loop;
end;
/
