create or replace force view cst_bof_gim_fin_msg_vw as
select f.id
     , f.status
     , f.file_id
     , f.record_number
     , f.is_reversal
     , f.is_incoming
     , f.is_returned
     , f.is_invalid
     , f.dispute_id
     , f.rrn
     , f.inst_id
     , f.network_id
     , f.trans_code
     , f.card_id
     , f.card_mask
     , f.card_hash
     , f.oper_amount
     , f.oper_currency
     , f.oper_date
     , f.sttl_amount
     , f.sttl_currency
     , f.arn
     , f.merchant_number
     , f.merchant_name
     , f.merchant_city
     , f.merchant_country
     , f.merchant_region
     , f.merchant_type
     , f.mcc
     , f.usage_code
     , f.reason_code
     , f.auth_code
     , f.crdh_id_method
     , f.chargeback_ref_num
     , f.docum_ind
     , f.member_msg_text
     , f.spec_cond_ind
     , f.terminal_number
     , f.electr_comm_ind
     , f.spec_chargeback_ind
     , f.account_selection
     , f.transaction_type
     , f.card_seq_number
     , f.terminal_profile
     , f.unpredict_number
     , f.appl_trans_counter
     , f.appl_interch_profile
     , f.cryptogram
     , f.term_verif_result
     , f.cryptogram_amount
     , f.issuer_appl_data
     , f.issuer_script_result
     , f.card_expir_date
     , f.cryptogram_info_data
     , f.acq_inst_bin
     , f.host_inst_id
     , f.proc_bin
     , f.terminal_country
     , f.electronic_term_ind
     , f.reconciliation_ind
     , f.payment_product_ind
     , f.crdh_cardnum_cap_ind
     , f.transaction_type_tcr3
     , f.trans_status
     , f.trans_code_header
     , f.trans_inter_proc_date
     , f.trans_date
     , f.trans_currency
     , f.trans_category_code
     , f.trans_seq_number
     , f.auth_code_src_ind
     , f.forw_inst_id
     , f.void_ind
     , f.receiv_inst_id
     , f.dest_amount
     , f.dest_currency
     , f.iss_reimb_fee
     , f.value_date
     , f.voucher_dep_bank_code
     , f.voucher_dep_branch_code
     , f.reconciliation_date
     , f.merch_serv_charge
     , f.acq_msc_revenue
     , f.crdh_billing_amount
     , f.cashback_amount
     , f.crdh_verif_method
     , f.terminal_type
     , f.iss_auth_data
     , f.rate_dst_loc_currency
     , f.rate_loc_dst_currency
     , f.logical_file
     , f.remittance_number
     , f.card_indicator
     , f.voucher_number
     , f.int_fee_amount
     , f.int_fee_currency
     , f.int_fee_sign
  from cst_bof_gim_fin_msg f
/
