package ru.bpc.sv2.application;

public interface ApplicationPrivConstants {
	String APPLICATION_FLOW						= "APPLICATION_FLOW";
	String VIEW_APPLICATION_FLOW				= "VIEW_APPLICATION_FLOW";
	String ADD_APPLICATION_FLOW					= "ADD_APPLICATION_FLOW";
	String MODIFY_APPLICATION_FLOW				= "MODIFY_APPLICATION_FLOW";
	String REMOVE_APPLICATION_FLOW				= "REMOVE_APPLICATION_FLOW";

	String APPLICATION_FLOW_STAGE				= "APPLICATION_FLOW_STAGE";
	String VIEW_APPLICATION_FLOW_STAGE			= "VIEW_APPLICATION_FLOW_STAGE";
	String ADD_APPLICATION_FLOW_STAGE			= "ADD_APPLICATION_FLOW_STAGE";
	String MODIFY_APPLICATION_FLOW_STAGE		= "MODIFY_APPLICATION_FLOW_STAGE";
	String REMOVE_APPLICATION_FLOW_STAGE		= "REMOVE_APPLICATION_FLOW_STAGE";

	String APPL_FLOW_TRANSITION					= "APPL_FLOW_TRANSITION";
	String VIEW_APPL_FLOW_TRANSITION			= "VIEW_APPL_FLOW_TRANSITION";
	String ADD_APPL_FLOW_TRANSITION				= "ADD_APPL_FLOW_TRANSITION";
	String MODIFY_APPL_FLOW_TRANSITION			= "MODIFY_APPL_FLOW_TRANSITION";
	String REMOVE_APPL_FLOW_TRANSITION			= "REMOVE_APPL_FLOW_TRANSITION";

	String APPLICATION_ELEMENT					= "APPLICATION_ELEMENT";
	String VIEW_APPLICATION_ELEMENT				= "VIEW_APPLICATION_ELEMENT";
	String ADD_APPLICATION_ELEMENT				= "ADD_APPLICATION_ELEMENT";

	String APPLICATION_FLOW_FILTER				= "APPLICATION_FLOW_FILTER";
	String VIEW_APPLICATION_FLOW_FILTER			= "VIEW_APPLICATION_FLOW_FILTER";
	String ADD_APPLICATION_FLOW_FILTER			= "ADD_APPLICATION_FLOW_FILTER";
	String MODIFY_APPLICATION_FLOW_FILTER		= "MODIFY_APPLICATION_FLOW_FILTER";
	String REMOVE_APPLICATION_FLOW_FILTER		= "REMOVE_APPLICATION_FLOW_FILTER";

	String APPLICATION_DEPENDENCY				= "APPLICATION_DEPENDENCY";
	String VIEW_APPLICATION_DEPENDENCY			= "VIEW_APPLICATION_DEPENDENCY";
	String VIEW_ALL_APPLICATIONS				= "VIEW_ALL_APPLICATIONS";
	String VIEW_PMO_APPLICATIONS				= "VIEW_PMO_APPLICATIONS";
	String VIEW_ACM_APPLICATIONS				= "VIEW_ACM_APPLICATION";
	String VIEW_APPLICATION_DATA				= "VIEW_APPLICATION_DATA";
	String VIEW_QUESTIONARY_APPLICATION         = "VIEW_QUESTIONARY_APPLICATION";

	String PROCESS_APPLICATION_FORCE			= "PROCESS_APPLICATION_FORCE";
	String CHANGE_DISPUTE_USER					= "CHANGE_DISPUTE_USER";
	String DISPUTE_APPLICATION_SUPERVISOR		= "DISPUTE_APPLICATION_SUPERVISOR";
	String CHECK_CASE_DUE_DATE					= "CHECK_CASE_DUE_DATE";
	String SET_CASE_DUE_DATE					= "SET_CASE_DUE_DATE";
	String ADD_DISPUTE_ATTACHMENT				= "ADD_DISPUTE_ATTACHMENT";

	String ISSUING_APPLICATION					= "ISSUING_APPLICATION";
	String VIEW_ISSUING_APPLICATION				= "VIEW_ISSUING_APPLICATION";
	String ADD_ISSUING_APPLICATION				= "ADD_ISSUING_APPLICATION";
	String MODIFY_ISSUING_APPLICATION			= "MODIFY_ISSUING_APPLICATION";
	String REMOVE_ISSUING_APPLICATION			= "REMOVE_ISSUING_APPLICATION";
	String PROCESS_ISSUING_APPLICATION			= "PROCESS_ISSUING_APPLICATION";
	String APPROVE_ISSUING_APPLICATION			= "APPROVE_ISSUING_APPLICATION";

	String ACQUIRING_APPLICATION				= "ACQUIRING_APPLICATION";
	String VIEW_ACQUIRING_APPLICATION			= "VIEW_ACQUIRING_APPLICATION";
	String ADD_ACQUIRING_APPLICATION			= "ADD_ACQUIRING_APPLICATION";
	String MODIFY_ACQUIRING_APPLICATION			= "MODIFY_ACQUIRING_APPLICATION";
	String REMOVE_ACQUIRING_APPLICATION			= "REMOVE_ACQUIRING_APPLICATION";
	String PROCESS_ACQUIRING_APPLICATION		= "PROCESS_ACQUIRING_APPLICATION";

	String DISPUTE_APPLICATIONS					= "DISPUTE_APPLICATIONS";
	String VIEW_DISPUTE_APPLICATIONS			= "VIEW_DISPUTE_APPLICATIONS";
	String ADD_DISPUTE_APPLICATIONS				= "ADD_DISPUTE_APPLICATIONS";
	String MODIFY_DISPUTE_APPLICATIONS			= "MODIFY_DISPUTE_APPLICATIONS";
	String REMOVE_DISPUTE_APPLICATIONS			= "REMOVE_DISPUTE_APPLICATIONS";
	String PROCESS_DISPUTE_APPLICATIONS			= "PROCESS_DISPUTE_APPLICATIONS";

	String FIN_REQUESTS							= "FIN_REQUESTS";
	String VIEW_FIN_REQUESTS					= "VIEW_FIN_REQUESTS";
	String PROCESS_FIN_REQUESTS					= "PROCESS_FIN_REQUESTS";

	String INSTITUTION_APPLICATION				= "INSTITUTION_APPLICATION";
	String VIEW_INSTITUTION_APPLICATION			= "VIEW_INSTITUTION_APPLICATION";
	String ADD_INSTITUTION_APPLICATION			= "ADD_INSTITUTION_APPLICATION";
	String MODIFY_INSTITUTION_APPLICATION		= "MODIFY_INSTITUTION_APPLICATION";
	String REMOVE_INSTITUTION_APPLICATION		= "REMOVE_INSTITUTION_APPLICATION";
	String PROCESS_INSTITUTION_APPLICATION		= "PROCESS_INSTITUTION_APPLICATION";

	String ACM_APPLICATION						= "ACM_APPLICATION";
	String VIEW_ACM_APPLICATION					= "VIEW_ACM_APPLICATION";
	String ADD_ACM_APPLICATION					= "ADD_ACM_APPLICATION";
	String MODIFY_ACM_APPLICATION				= "MODIFY_ACM_APPLICATION";
	String REMOVE_ACM_APPLICATION				= "REMOVE_ACM_APPLICATION";
	String PROCESS_ACM_APPLICATION				= "PROCESS_ACM_APPLICATION";
	String QUESTIONARY_APPLICATION				= "QUESTIONARY_APPLICATION";
	String ADD_QUESTIONARY_APPLICATION			= "ADD_QUESTIONARY_APPLICATION";

	String ISS_PRD_APPLICATION					= "ISS_PRD_APPLICATION";
	String VIEW_ISS_PRD_APPLICATION				= "VIEW_ISS_PRD_APPLICATION";
	String ADD_ISS_PRD_APPLICATION				= "ADD_ISS_PRD_APPLICATION";
	String MODIFY_ISS_PRD_APPLICATION			= "MODIFY_ISS_PRD_APPLICATION";
	String REMOVE_ISS_PRD_APPLICATION			= "REMOVE_ISS_PRD_APPLICATION";
	String PROCESS_ISS_PRD_APPLICATION			= "PROCESS_ISS_PRD_APPLICATION";

	String ACQ_PRD_APPLICATION					= "ACQ_PRD_APPLICATION";
	String VIEW_ACQ_PRD_APPLICATION				= "VIEW_ACQ_PRD_APPLICATION";
	String ADD_ACQ_PRD_APPLICATION				= "ADD_ACQ_PRD_APPLICATION";
	String MODIFY_ACQ_PRD_APPLICATION			= "MODIFY_ACQ_PRD_APPLICATION";
	String REMOVE_ACQ_PRD_APPLICATION			= "REMOVE_ACQ_PRD_APPLICATION";
	String PROCESS_ACQ_PRD_APPLICATION			= "PROCESS_ACQ_PRD_APPLICATION";

	String CAMPAIGN_APPLICATION					= "CAMPAIGN_APPLICATIONS";
	String VIEW_CAMPAIGN_APPLICATION			= "VIEW_CAMPAIGN_APPLICATIONS";
	String ADD_CAMPAIGN_APPLICATION				= "ADD_CAMPAIGN_APPLICATIONS";
	String MODIFY_CAMPAIGN_APPLICATION			= "MODIFY_CAMPAIGN_APPLICATIONS";
	String REMOVE_CAMPAIGN_APPLICATION			= "REMOVE_CAMPAIGN_APPLICATIONS";
	String PROCESS_CAMPAIGN_APPLICATION			= "PROCESS_CAMPAIGN_APPLICATIONS";

	String VIEW_EVALUATION_CRITERIA				= "VIEW_EVALUATION_CRITERIA";
}
