package ru.bpc.sv2.utils;

public interface AuthOracleTypeNames {
	String AUTH = "AUT_AUTHORIZATION_TYP";
	String AUTH_SET = "AUT_AUTHORIZATION_TAB_TYP";

	String APP_DATA_REC = "APP_DATA_TPR";
	String APP_DATA_TAB = "APP_DATA_TPT";

	String COM_PARAM_MAP_REC = "COM_PARAM_MAP_TPR";
	String COM_PARAM_MAP_TAB = "COM_PARAM_MAP_TPT";

	String PRC_SESSION_FILE_RAW_REC = "RAW_DATA_TPR";
	String PRC_SESSION_FILE_RAW_TAB = "RAW_DATA_TPT";

	String PRC_SESSION_FILE_RECNUM_TAB = "NUM_TAB_TPT";
	String PRC_SESSION_FILE_TAB = "PRC_SESSION_FILE_TAB";
	String PRC_SESSION_FILE_RECNUM = "PRC_SESSION_FILE_RECNUM";

	String OPR_OPERATION_REC = "OPR_OPERATION_TPR";
	String OPR_OPERATION_TAB = "OPR_OPERATION_TPT";

	String CST_BASE24_OPERATION_RECONCILATION_REC = "CST_BASE24_RECON_TPR";
	String CST_BASE24_OPERATION_RECONCILATION_TAB = "CST_BASE24_RECON_TPT";

	String DICT_TAB_TPR = "COM_DICT_TPR";
	String DICT_TAB_TPT = "COM_DICT_TPT";

	String T_OPER_CLEARING_REC = "OPER_CLEARING_TPR";
	String T_OPER_CLEARING_TAB = "OPER_CLEARING_TPT";

	String RCN_RECON_MSG_REC = "RCN_RECON_MSG_TPR";
	String RCN_RECON_MSG_TAB = "RCN_RECON_MSG_TPT";

	String RCN_ADDL_AMOUNT_REC = "RCN_ADDITIONAL_AMOUNT_TPR";
	String RCN_ADDL_AMOUNT_TAB = "RCN_ADDITIONAL_AMOUNT_TPT";

	String RCN_ATM_RECON_MSG_REC = "RCN_ATM_RECON_MSG_TPR";
	String RCN_ATM_RECON_MSG_TAB = "RCN_ATM_RECON_MSG_TPT";

	String RCN_HOST_RECON_MSG_REC = "RCN_HOST_RECON_MSG_TPR";
	String RCN_HOST_RECON_MSG_TAB = "RCN_HOST_RECON_MSG_TPT";

	String RCN_NAT_SWITCH_RECON_MSG_REC = "RCN_NAT_SWITCH_RECON_MSG_TPR";
	String RCN_NAT_SWITCH_RECON_MSG_TAB = "RCN_NAT_SWITCH_RECON_MSG_TPT";

	String RCN_SRVP_RECON_MSG_REC = "RCN_SRVP_MSG_TPR";
	String RCN_SRVP_RECON_MSG_TAB = "RCN_SRVP_MSG_TPT";

	String ACM_USER_DATA_REC = "ACM_USER_DATA_TPR";
	String ACM_USER_DATA_TAB = "ACM_USER_DATA_TPT";

	String COM_TRANSLATION_TEXT_REC = "COM_TEXT_TRANS_TPR";
	String COM_TRANSLATION_TEXT_TAB = "COM_TEXT_TRANS_TPT";

	String PMO_RESPONSE_REC = "PMO_RESPONSE_TPR";
	String PMO_RESPONSE_TAB = "PMO_RESPONSE_TPT";

	String AUP_TAG_REC = "AUP_TAG_VALUE_TPR";
	String AUP_TAG_TAB = "AUP_TAG_VALUE_TPT";

	String AUTH_DATA_REC = "AUTH_DATA_TPR";
	String AUTH_DATA_TAB = "AUTH_DATA_TPT";

	String AUTH_TAG_REC = "AUTH_TAG_TPR";
	String AUTH_TAG_TAB = "AUTH_TAG_TPT";

	String MCW_MCOM_CLAIM_REC = "MCW_MCOM_CLAIM_TPR";
	String MCW_MCOM_CLAIM_TAB = "MCW_MCOM_CLAIM_TPT";

	String MCW_MCOM_CHARGEBACK_REC = "MCW_MCOM_CHBCK_TPR";
	String MCW_MCOM_CHARGEBACK_TAB = "MCW_MCOM_CHBCK_TPT";

	String MCW_MCOM_RETRIEVAL_REC = "MCW_MCOM_RETRIEVAL_TPR";
	String MCW_MCOM_RETRIEVAL_TAB = "MCW_MCOM_RETRIEVAL_TPT";

	String MCW_MCOM_FEE_REC = "MCW_MCOM_FEE_TPR";
	String MCW_MCOM_FEE_TAB = "MCW_MCOM_FEE_TPT";
}
