spring:
  datasource:
#    jndi-name:
#    jndi-name: jdbc/SVWeb
#    driver-class-name: weblogic.jdbc.jts.Driver
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@rnd-sv2-test9.bt.bpc.in:1521:sv
#    username: main
#    password: main1
