insert into utl_table (TABLE_NAME, TABLESPACE_NAME, IS_CONFIG_TABLE, CONFIG_CONDITION, IS_SPLIT_SEQ, IS_CLEANUP_TABLE, SYNCH_GROUP) values ('CST_AMK_EPW_FILE', 'TRANS_DATA_TBS', '0', null, '0', '1', null)
/
insert into utl_table (TABLE_NAME, TABLESPACE_NAME, IS_CONFIG_TABLE, CONFIG_CONDITION, IS_SPLIT_SEQ, IS_CLEANUP_TABLE, SYNCH_GROUP) values ('CST_AMK_EPW_FIN_MSG', 'TRANS_DATA_TBS', '0', null, '0', '1', null)
/

