insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (195, NULL, 'select a.id as code,a.short_desc as name, a.priv_id  from acm_ui_priv_limitation_vw a where a.lang = get_user_lang', 'ACM', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 1)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (249, NULL, 'select id code, label name, entity_type from acm_ui_action_group_vw where lang = com_ui_user_env_pkg.get_user_lang', 'ACM', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 1)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (250, NULL, 'select id, label name, entity_type from acm_ui_action_vw where group_id is null and lang = com_ui_user_env_pkg.get_user_lang', 'ACM', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 1)
/
delete com_lov where id = 266
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values ( 266, NULL, 'select dict||code  ascode, name, ''ENTTACCT'' entity_type from com_ui_dictionary_vw where dict = ''ACTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTAGNT'' entity_type from com_ui_dictionary_vw where dict = ''AGTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTAUTH'' entity_type from com_ui_dictionary_vw where dict = ''MSGT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTBLNC'' entity_type from com_ui_dictionary_vw where dict = ''BLTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTCNTC'' entity_type from com_ui_dictionary_vw where dict = ''CNTT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTCNTR'' entity_type from com_ui_dictionary_vw where dict = ''CNTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTCUST'' entity_type from com_ui_dictionary_vw where dict = ''ENTT'' and code in (''COMP'',''PERS'',''UNDF'') and lang = get_user_lang union  all select dict||code code, name, ''ENTTFILE'' entity_type from com_ui_dictionary_vw where dict = ''FLTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTMRCH'' entity_type from com_ui_dictionary_vw where dict = ''MRCT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTOPER'' entity_type from com_ui_dictionary_vw where dict = ''OPTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTPROD'' entity_type from com_ui_dictionary_vw where dict = ''PRDT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTTRMN'' entity_type from com_ui_dictionary_vw where dict = ''TRMT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTDCMT'' entity_type from com_ui_dictionary_vw where dict = ''DCMT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTTRSC'' entity_type from com_ui_dictionary_vw where dict = ''TRNT'' and lang = get_user_lang', 'ACM', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 1)
/
update com_lov set lov_query='select dict||code  as code, name, ''ENTTACCT'' entity_type from com_ui_dictionary_vw where dict = ''ACTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTAGNT'' entity_type from com_ui_dictionary_vw where dict = ''AGTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTAUTH'' entity_type from com_ui_dictionary_vw where dict = ''MSGT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTBLNC'' entity_type from com_ui_dictionary_vw where dict = ''BLTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTCNTC'' entity_type from com_ui_dictionary_vw where dict = ''CNTT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTCNTR'' entity_type from com_ui_dictionary_vw where dict = ''CNTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTCUST'' entity_type from com_ui_dictionary_vw where dict = ''ENTT'' and code in (''COMP'',''PERS'',''UNDF'') and lang = get_user_lang union  all select dict||code code, name, ''ENTTFILE'' entity_type from com_ui_dictionary_vw where dict = ''FLTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTMRCH'' entity_type from com_ui_dictionary_vw where dict = ''MRCT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTOPER'' entity_type from com_ui_dictionary_vw where dict = ''OPTP'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTPROD'' entity_type from com_ui_dictionary_vw where dict = ''PRDT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTTRMN'' entity_type from com_ui_dictionary_vw where dict = ''TRMT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTDCMT'' entity_type from com_ui_dictionary_vw where dict = ''DCMT'' and lang = get_user_lang union  all select dict||code code, name, ''ENTTTRSC'' entity_type from com_ui_dictionary_vw where dict = ''TRNT'' and lang = get_user_lang' where id = 266
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (386, NULL, 'select id code, short_desc name from acm_ui_privilege_vw where lang = get_user_lang', 'ACM', 'LVSMCODE', 'LVAPCDNM', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (425, NULL, 'select id code, label name, priv_id from acm_ui_priv_limitation_vw where lang = get_user_lang', 'ACM', 'LVSMNAME', 'LVAPNAME', 'DTTPNMBR', 1)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (1035, NULL, 'select id code, name from com_ui_lov_vw where (lov_query is null or lower(lov_query) like ''%com_ui_dict%'') and data_type = ''DTTPCHAR'' and lang = get_user_lang', 'ACM', 'LVSMNAME', 'LVAPNAME', 'DTTPNMBR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (447, NULL, 'select id code, action name from acm_section_vw', 'ACM', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0)
/
update com_lov set lov_query = 'select id code, action name from acm_section_vw where lower(section_type) = ''page''' where id = 447
/
update com_lov set lov_query = 'select a.id as code,a.label as name, a.priv_id  from acm_ui_priv_limitation_vw a where a.lang = get_user_lang' where id = 195
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized) values (1047, 'USST', NULL, 'ACM', 'LVSMCODE', 'LVAPNMCD', 'DTTPCHAR', 0)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized, is_depended) values (647, NULL, 'select distinct user_id as code, surname ||'' ''|| first_name as name from acm_ui_user_vw where inst_id in (select inst_id from acm_cu_inst_vw)', 'ACM', 'LVSMCODE', 'LVAPNAME', 'DTTPNMBR', 0, NULL)
/
update com_lov set lov_query = lov_query || ' union all select -1, ''Not assigned'' from dual'  where id = 647
/
update com_lov set lov_query = lov_query || 'select distinct user_id as code, surname ||'' ''|| first_name as name from acm_ui_user_vw where inst_id in (select inst_id from acm_cu_inst_vw) union all select -1, ''UNDEFINED'' from dual'  where id = 647
/
update com_lov set lov_query = 'select distinct user_id as code, surname ||'' ''|| first_name as name from acm_ui_user_vw where inst_id in (select inst_id from acm_cu_inst_vw) union all select -1, ''UNDEFINED'' from dual'  where id = 647
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized, is_depended) values (711, 'PRLM', NULL, 'ACM', 'LVSMCODE', 'LVAPCDNM', 'DTTPCHAR', 0, NULL)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized, is_depended) values (715, NULL, 'select g.id as code, g.description as name from acm_ui_group_vw g where g.lang = com_ui_user_env_pkg.get_user_lang union all select 99999999 code, com_api_label_pkg.get_label_text (''SYS_GROUP_NAME'', b.lang) name from com_language_vw b where b.lang = com_ui_user_env_pkg.get_user_lang', 'ACM', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 0, NULL)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized, is_depended) values (716, NULL, 'select distinct u.user_id as code, u.surname ||'', ''|| u.first_name ||'' ''|| u.second_name as name, up.priv_name from acm_ui_user_privilege_all_vw up, acm_ui_user_vw u where u.user_id = up.user_id and up.lang = get_user_lang and u.lang = get_user_lang', 'ACM', 'LVSMNAME', 'LVAPNAME', 'DTTPCHAR', 1, NULL)
/
insert into com_lov (id, dict, lov_query, module_code, sort_mode, appearance, data_type, is_parametrized, is_depended) values (718, NULL, 'select ''CARD_MASK'' code, ''Card mask'' name from dual union all select ''HOST_DATE_FROM'', ''Host date from'' name from dual union all select ''HOST_DATE_TILL'', ''Host date till'' name from dual', 'ACM', 'LVSMCODD', 'LVAPCDNM', 'DTTPCHAR', 0, NULL)
/
update com_lov set lov_query ='select id code, label name, priv_id, limitation_type from acm_ui_priv_limitation_vw where lang = get_user_lang' where id = 425
/
update com_lov set lov_query = 'select name as code, get_text(''RUL_MOD_PARAM'', ''SHORT_DESCRIPTION'', id, get_user_lang) as name from rul_mod_param where name in (''CARD_MASK'', ''HOST_DATE_FROM'', ''HOST_DATE_TILL'', ''ORDER_DATE_FROM'')' where id = 718
/
update com_lov set lov_query = 'select name as code, get_text(''RUL_MOD_PARAM'', ''SHORT_DESCRIPTION'', id, get_user_lang) as name from rul_mod_param where name in (''CARD_MASK'', ''HOST_DATE_FROM'', ''HOST_DATE_TILL'', ''ORDER_DATE_FROM'', ''ORDER_DATE_TO'')' where id = 718
/
