package ru.bpc.sv2.constants;

public interface SectionIdConstants {
	String ISSUING_ACCOUNT	 				= "1011";
	String ISSUING_PERSONALIZATION_BATCH 	= "1413";
	String ISSUING_APPLICATION				= "1014";
	String ISSUING_BLACK_LIST				= "2310";
	String ISSUING_CARD						= "1012";
	String ISSUING_CARDHOLDER				= "1013";
	String ISSUING_OPERATION				= "1008";
	String ISSUING_PERSO_METHOD				= "1373";
	String ISSUING_PERSO_KEY_SCHEMA			= "1374";
	String ISSUING_PERSO_CERT_AUTH			= "2272";
	String ISSUING_CONFIG_BIN				= "1393";
	String ISSUING_CONFIG_PRODUCT			= "1016";
	String ISSUING_CREDIT_PAYMENT			= "2082";
	String ISSUING_CREDIT_DEBT				= "1982";
	String ISSUING_CREDIT_PAYMENT_PLAN		= "2223";
	String ISSUING_CREDIT_INVOICE			= "1698";
	String ISSUING_EMV_CARD					= "2302";
	String ISSUING_EMV_SCHEME				= "2268";
	String ISSUING_EMV_APP					= "2269";
	String ISSUING_RSA_CERT					= "2281";
	String ISSUING_RSA_KEY					= "2284";
	String ISSUING_DELIVERY					= "2413";

	String ACQUIRING_ACCOUNT				= "1022";
	String ACQUIRING_MERCHANT				= "1019";
	String ACQUIRING_TERMINAL				= "1021";
	String ACQUIRING_APPLICATION			= "1023";
	String ACQUIRING_HIERACHY				= "1696";
	String ACQUIRING_OPERATION				= "1018";
	String ACQUIRING_CONFIG_SCHEME			= "1699";
	String ACQUIRING_CONFIG_PRODUCT			= "1024";
	String ACQUIRING_REIMB_BATCH			= "1114";
	String ACQUIRING_VCH_BATCH				= "2282";
	String ACQUIRING_MCC_REF_GROUP			= "2305";

	String CUSTOMER_CUSTOMER				= "1677";
	String CUSTOMER_CONTRACT				= "1678";

	String MONITORING_AUDIT_LOG 			= "1029";
	String MONITORING_PROCESS_LOG 			= "1028";
	String MONITORING_PROCESS_FILES			= "2321";
	String MONITORING_REPORT				= "1513";
	String MONITORING_USER_SESSION			= "1615";
	String MONITORING_ATM					= "2285";

	String CONFIGURATION_FEE_FEE			= "1057";
	String CONFIGURATION_RATE_RATE			= "1133";
	String CONFIGURATION_CYCLE_CYCLE		= "1049";
	String CONFIGURATION_RATE_TYPE			= "1132";
	String CONFIGURATION_CARD_TYPE			= "1334";
	String CONFIGURATION_SERVICING_TYPE		= "1658";
	String CONFIGURATION_SERVICING_TERM		= "1657";
	String CONFIGURATION_SERVICING_SERVICE	= "1659";
	String CONFIGURATION_NOTIF_SCHEME		= "1574";
	String CONFIGURATION_NOTIF_NOTIF		= "1575";
	String CONFIGURATION_NOTIF_EVENT		= "1613";
	String CONFIGURATION_RPT_REPORT			= "1493";
	String CONFIGURATION_RPT_TAG			= "2275";
	String CONFIGURATION_ARR_ARR			= "1903";
	String CONFIGURATION_ARR_CONV			= "1922";
	String CONFIGURATION_APP_FLOW			= "2003";

	String REVENUE_SHARING					= "1133";

	String PAYMENT_ORDERS_APPLICATION		= "2307";
	String INSTITUTION_APPLICATION			= "2427";
	String ISSUING_PRODUCT_APPLICATION		= "2444";
	String ACQUIRING_PRODUCT_APPLICATION	= "2446";
	String QUESTIONARY_APPLICATION			= "7003";
	String CAMPAIGNS_APPLICATION			= "2471";

	String STRUCT_ORG_ACC					= "2162";
	String STRUCT_ORG_INST					= "1037";
	String STRUCT_ORG_AGENT					= "1038";
	String STRUCT_NET_NET					= "1231";
	String STRUCT_NET_HOST					= "1232";

	String OPERATION_ACC_ALGORITHM			= "1655";
	String OPERATION_ACC_ACCTYPE			= "1041";
	String OPERATION_PROCESSING_PROCEDURE	= "1045";
	String OPERATION_PROCESSING_RULE		= "1046";
	String OPERATION_PROCESSING_TEMPLATE	= "1047";
	String OPERATION_PROCESSING_OPERTYPE	= "2288";
	String OPERATION_AUTH_SCENARIO			= "1083";
	String OPERATION_AUTH_SCHEME			= "1862";
	String OPERATION_NAMING_FORMAT			= "1191";
	String OPERATION_NAMING_RANGE			= "1210";
	String OPERATION_EVENT_TYPE				= "1291";
	String OPERATION_EVENT_EVENT			= "1292";
	String OPERATION_MATCHING_LEVEL			= "1434";
	String OPERATION_MODIFIER_SCALE			= "1090";
	String OPERATION_CHECK_GROUP			= "1742";
	String OPERATION_CHECK_SELECTION		= "1743";

	String PAYMENT_ORDER_PROVIDER			= "2142";
	String PAYMENT_ORDER_PARAMETER			= "2182";

	String ROUTING_OPERATION				= "2448";

	String FRAU_PREVENTION_CASES			= "1803";

	String ADMINISTRATION_DICTIONARY		= "1074";
	String HSM_DEVICE						= "1086";
	String ADMIN_INTERFACE_ACTION			= "2023";
	String ADMIN_INTERFACE_ACTION_GROUP		= "2274";
	String ADMIN_PERMISSION_PRIVILEGE		= "1078";
	String ADMIN_PERMISSION_ROLE			= "1079";
	String ADMIN_PERMISSION_USER			= "1080";
	String ADMIN_PROCESS_GROUP				= "1072";
	String ADMIN_PROCESS_PROCESS			= "1070";
	String ADMIN_PROCESS_CONTAINER			= "1068";

	String ADMIN_COMMU_STANDARD				= "1117";
	String ADMIN_COMMU_DEVICE				= "1170";
	String ADMIN_PARTITION_TABLE			= "2308";

	String MC_ABU_FILES						= "2459";
}
